### ISSUE TITLE
get() requires callback functions but got a [object Undefined]

### ISSUE THREAD

**Issue by jrcscarrillo** [nodeschool/discussions#1011]
I am learning node.js. Please help me with this.

My app.js

```JavaScript
/**
 * Module dependencies.
 */

var express = require('express');
var routes = require('./routes');
var http = require('http');
var path = require('path');

var app = express();

// all environments
app.set('port', process.env.PORT || 3000);
app.set('views', __dirname + '/views');
app.set('view engine', 'jade');
app.use(express.favicon());
app.use(express.logger('dev'));
app.use(express.bodyParser());
app.use(express.methodOverride());
app.use(app.router);
app.use(express.static(path.join(__dirname, 'public')));

// development only
if ('development' == app.get('env')) {
  app.use(express.errorHandler());
}

app.get('/flight/:number', routes.flight);

http.createServer(app).listen(app.get('port'), function(){
  console.log('Express server listening on port ' + app.get('port'));
});

My index.js


/*
 * GET home page.
 */

var flight = require('../flight');
var flights = require('../data');

for ( var nroVuelo in flights ) {
    flights[nroVuelo] = flight(flights[nroVuelo]);
}
exports.flight = function(req, res){
    var nroVuelo = req.param('number');
    if ( typeof flights[nroVuelo] === 'undefined') {
        res.status(404).json({ status: 'error'});
    } else {
        res.json( flights[nroVuelo].getInformation() );
    }
};
```

The error:
```
C:\Users\Juan\Desktop\exercise5_3\node_modules\express\lib\router\index.js:290
    throw new Error(msg);
          ^
Error: .get() requires callback functions but got a [object Undefined]
    at C:\Users\Juan\Desktop\exercise5_3\node_modules\express\lib\router\index.js:290:11
    at Array.forEach (native)
    at Router.route (C:\Users\Juan\Desktop\exercise5_3\node_modules\express\lib\router\index.js:286:13)
    at Router.(anonymous function) [as get] (C:\Users\Juan\Desktop\exercise5_3\node_modules\express\lib\router\index.js:308:16)
    at Function.app.(anonymous function) (C:\Users\Juan\Desktop\exercise5_3\node_modules\express\lib\application.js:414:26)
    at Object.<anonymous> (C:\Users\Juan\Desktop\exercise5_3\app.js:30:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

**Comment by sudodoki** [comment]
Line numbers are messed up, but wouldn't issue be in `app.get('port')`?
