### ISSUE TITLE
MY FIRST I/O issue with fs.js?

### ISSUE THREAD

**Issue by joshbivens** [nodeschool/discussions#1015]
This code

```JavaScript
var fs = require('fs');
var buf = fs.readFileSync(process.argv);
var str = buf.toString();
var arr = str.split('\n');					
console.log(arr.length - 1);
```

results in this error:

    fs.js:502
      return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                     ^
    TypeError: path must be a string
        at TypeError (native)
        at Object.fs.openSync (fs.js:502:18)
        at Object.fs.readFileSync (fs.js:354:15)
        at Object.<anonymous> (/Users/joshbivens/Desktop/learnyounode/fs_buffer.js:3:14)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Function.Module.runMain (module.js:501:10)
        at startup (node.js:129:16)

What's wrong? The error is in the fs.js...

**Comment by blakmatrix** [comment]
@joshbivens `process.argv` is an array, did you mean to use `process.argv[2]`

**Comment by joshbivens** [comment]
Ah! Thank you! Yes.

**Comment by g3hk** [comment]
kindly remove me from this mail loop
