### ISSUE TITLE
node module.js generates error. 

### ISSUE THREAD

**Issue by palashCItobuz** [nodeschool/discussions#1019]
I am a newbie to node.js. In the node REPL everything was working fine. But something changed. It seems I deleted some random. Not sure if that's the reason, but when I try to execute a file it shows this...
```
D:\Projects-2015\uniqueva>node
>node module.js


SyntaxError: Unexpected identifier
    at Object.exports.createScript (vm.js:44:10)
    at REPLServer.defaultEval (repl.js:117:23)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
    at REPLServer.Interface._onLine (readline.js:214:10)
    at REPLServer.Interface._line (readline.js:553:8)
    at REPLServer.Interface._ttyWrite (readline.js:830:14)
    at ReadStream.onkeypress (readline.js:109:10)
```

**Comment by Sequoia** [comment]
hi @palashCItobuz! So when you are **in** the node REPL (the "node command line", the one with just the `>` as a prompt), you are feeding commands *directly to node*, which interprets javascript.  What I mean to say is "don't call `node` from within `node`."  If you want to run `module.js`, run `node module.js` **from your shell** not from node.

## Try this
```
D:\Projects-2015\uniqueva> node module.js
```

## Extra
in the node-command-line you can enter JS. Try it out!
```
> '  .dlrow olleH  '.split('').reverse().join('').trim();
'Hello world.'
```

Keep us posted!

**Comment by palashCItobuz** [comment]
@Sequoia Yes, that was the issue as I figured it out. Thanks for your help! :+1:
