### ISSUE TITLE
Cannot  switch to old mode now error

### ISSUE THREAD

**Issue by EfthiasSoftware** [nodeschool/discussions#1067]
when i type learnyounode i get following error
stream_readable.js:749
    throw new Error('Cannot switch to old mode now.');
          ^
Error: Cannot switch to old mode now.
    at emitDataEvents (_stream_readable.js:749:11)
    at ReadStream.Readable.resume (_stream_readable.js:734:3)
    at showMenu (/usr/lib/node_modules/learnyounode/node_modules/workshopper/menu.js:90:17)
    at showMenu (/usr/lib/node_modules/learnyounode/node_modules/workshopper/exerciseMenu.js:29:10)
    at Workshopper.printMenu (/usr/lib/node_modules/learnyounode/node_modules/workshopper/workshopper.js:355:14)
    at new Workshopper (/usr/lib/node_modules/learnyounode/node_modules/workshopper/workshopper.js:180:8)
    at Workshopper (/usr/lib/node_modules/learnyounode/node_modules/workshopper/workshopper.js:22:12)
    at Object.<anonymous> (/usr/lib/node_modules/learnyounode/learnyounode.js:11:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

**Comment by finnp** [comment]
Hey, you should be able to fix this by installing the most recent version of node from nodejs.org
