### ISSUE TITLE
Get stuck with learnyounode installation

### ISSUE THREAD

**Issue by PhanHoangAnh** [nodeschool/discussions#1070]
I'd follow instruction of installation for learnyounode in both operating system: Win 8.1 and Ubuntu 14.2
both of them display message like bellow:

D:\>learnyounode

_stream_readable.js:748
    throw new Error('Cannot switch to old mode now.');
          ^
Error: Cannot switch to old mode now.
    at emitDataEvents (_stream_readable.js:748:11)
    at ReadStream.Readable.resume (_stream_readable.js:733:3)
    at showMenu (C:\Users\NHNN\AppData\Roaming\npm\node_modules\learnyounode\nod
e_modules\workshopper\menu.js:90:17)
    at showMenu (C:\Users\NHNN\AppData\Roaming\npm\node_modules\learnyounode\nod
e_modules\workshopper\exerciseMenu.js:29:10)
    at Workshopper.printMenu (C:\Users\NHNN\AppData\Roaming\npm\node_modules\lea
rnyounode\node_modules\workshopper\workshopper.js:355:14)
    at new Workshopper (C:\Users\NHNN\AppData\Roaming\npm\node_modules\learnyoun
ode\node_modules\workshopper\workshopper.js:180:8)
    at Workshopper (C:\Users\NHNN\AppData\Roaming\npm\node_modules\learnyounode\
node_modules\workshopper\workshopper.js:22:12)
    at Object.<anonymous> (C:\Users\NHNN\AppData\Roaming\npm\node_modules\learny
ounode\learnyounode.js:11:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

Please help and tell me what I should do...
Thank in Advance

**Comment by martinheidegger** [comment]
Right now we have a bug that breaks learnyounode on node v < 0.12

**Comment by martinheidegger** [comment]
Known & Duplicate
