### ISSUE TITLE
Cannot switch to old mode now

### ISSUE THREAD

**Issue by lamujeresponja** [nodeschool/discussions#1071]
Hi all.

In learnyounode workshop appear the next error:

_stream_readable.js:730
    throw new Error('Cannot switch to old mode now.');
          ^
Error: Cannot switch to old mode now.
    at emitDataEvents (_stream_readable.js:730:11)
    at ReadStream.Readable.resume (_stream_readable.js:715:3)
    at showMenu (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper/menu.js:90:17)
    at showMenu (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper/exerciseMenu.js:29:10)
    at Workshopper.printMenu (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper/workshopper.js:355:14)
    at new Workshopper (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper/workshopper.js:180:8)
    at Workshopper (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper/workshopper.js:22:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/learnyounode/learnyounode.js:11:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

I have got node.js 0.10.26

Thanks you
Elvira

**Comment by martinheidegger** [comment]
We have a bug when starting learnyounode with versions of node < 0.12 Please update for the time beeing, sorry for the inconvenience.

**Comment by finnp** [comment]
PS: You can solve this by downloaded the most reent node version from the website: https://nodejs.org/
