### ISSUE TITLE
Error: Cannot switch to old mode now. When try to run learnyounode

### ISSUE THREAD

**Issue by gsambrotta** [nodeschool/discussions#1072]
Hi. I just install learnyounode workshop with command:

`npm install -g learnyounode`

but as soon as I run `learnyounode` i got this error:

```MBP-di-giorgia:buzzfeed anaketa$ learnyounode

_stream_readable.js:748
    throw new Error('Cannot switch to old mode now.');
          ^
Error: Cannot switch to old mode now.
    at emitDataEvents (_stream_readable.js:748:11)
    at ReadStream.Readable.resume (_stream_readable.js:733:3)
    at showMenu (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper/menu.js:90:17)
    at showMenu (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper/exerciseMenu.js:29:10)
    at Workshopper.printMenu (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper/workshopper.js:355:14)
    at new Workshopper (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper/workshopper.js:180:8)
    at Workshopper (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper/workshopper.js:22:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/learnyounode/learnyounode.js:11:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)```

Any ideas why?

**Comment by finnp** [comment]
Hey @gsambrotta ,

this appears to be a pretty new problem with node 0.10. You should be able to fix this by installing the most recent version (0.12) of nodejs, which you can download here: https://nodejs.org/

However please open an issue over here as well https://github.com/rvagg/learnyounode/issues, so this problem can be fixed for node 0.10

Best,
Finn

**Comment by gsambrotta** [comment]
Hey thanks, actually i notice other 2 similar issue as soon as i create mine :)
I'm updating my node and I will open an issue on the learyounode repo as well.
Thanks

**Comment by gsambrotta** [comment]
One other question
To update node is actually better to uninstall and re-install it or instead to use tools like nvm https://github.com/creationix/nvm?

**Comment by finnp** [comment]
Installing from the website is fine. But using nvm is actually quite easy and allows you to switch between different versions and have different versions installed on your system.
For example to replicate this issue I did:
```
nvm install 0.10.32
nvm use 0.10.32 
``
Try it out, if you want.

**Comment by gsambrotta** [comment]
cool! thanks

**Comment by finnp** [comment]
If you have problems with it, just post an issue here or at the nvm repo :beetle:
