### ISSUE TITLE
Click "space" and "Enter" from terminal menu, get unhandled 'error': write after end

### ISSUE THREAD

**Issue by dylanwind** [nodeschool/discussions#1084]
I searched the issue by filter with “write after end”, but didn't find related one. 
So I open a new one here.

The issue is, 
* open CMD, 
* type "learnyounode", the terminal menu display.
* now click "space", the menu disappear, 
* then click "enter", 
* get below error output:
```
_events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write after end
    at writeAfterEnd (C:\Users\<myName>\AppData\Roaming\npm\node_modules\learnyounode\node
_modules\workshopper\node_modules\terminal-menu\node_modules\duplexer2\node_modules\readab
le-stream\lib\_stream_writable.js:161:12)
    at DuplexWrapper.Writable.write (C:\Users\<myName>\AppData\Roaming\npm\node_modules\le
arnyounode\node_modules\workshopper\node_modules\terminal-menu\node_modules\duplexer2\node
_modules\readable-stream\lib\_stream_writable.js:208:5)
    at ReadStream.passDataToMenu (C:\Users\<myName>\AppData\Roaming\npm\node_modules\learn
younode\node_modules\workshopper\menu.js:69:16)
    at ReadStream.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at ReadStream.Readable.push (_stream_readable.js:126:10)
    at TTY.onread (net.js:538:20)_
```
Thanks,
Dylan

**Comment by SomeoneWeird** [comment]
Can confirm, latest on OSX.

**Comment by finnp** [comment]
I can confirm this as well. You can use "Enter" then it works as expected.

However this is a bug. Could you open another issue on https://github.com/rvagg/workshopper? You can just copy and paste what you wrote here.

**Comment by dylanwind** [comment]
Open an issue: https://github.com/rvagg/workshopper/issues/108

**Comment by martinheidegger** [comment]
@dylanwind Thanks a lot!
