### ISSUE TITLE
Filtered LS Help: Path.extname not working

### ISSUE THREAD

**Issue by mitchell-massey** [nodeschool/discussions#1105]
# How can I correct this problem in 5 / 13 ? 

Error message:
---------
```
/Users/mitchellmassey/Sites/node/filtls.js:7
		if (dirpath.extname(list[i]) === ext){
		            ^
TypeError: undefined is not a function
    at callback (/Users/mitchellmassey/Sites/node/filtls.js:7:15)
    at FSReqWrap.oncomplete (fs.js:95:15)
```

✗ Submission results did not match expected!
✓ Used asynchronous method: fs.readdir()

Code:
---------
```javascript
var fs = require('fs');
var dirpath = process.argv[2];
var ext = process.argv[3];

fs.readdir(dirpath, function callback (err, list) {
        for (i=0; i<list.length; i++){
                if (dirpath.extname(list[i]) === ext){
                        console.log(list[i]);
                };
        };
});
```

**Comment by dominhhai** [comment]
Your `dirpath ` is a `String`, it don't have `extname` method.
To extract extension of a file, you can use `path` module with its `extname` method.
Check it [here](https://nodejs.org/api/path.html#path_path_extname_p)

**Comment by mitchell-massey** [comment]
Thanks! That cleared everything up.
