### ISSUE TITLE
learnyoureact first exercise - Unexpected token

### ISSUE THREAD

**Issue by rbusquet** [nodeschool/discussions#1142]
Hello, I'm going through some tutorials and now I'm stucked in learyoureact;.

I tried to write the code by my own, and got this error:
```
D:\learnnode\react\views\index.jsx:6
     <div className="todoBox">
     ^
SyntaxError: Unexpected token <
   at exports.runInThisContext (vm.js:73:16)
   at Module._compile (module.js:443:25)
   at Module._extensions..js (module.js:478:10)
   at Object.require.extensions.(anonymous function) [as .jsx] (D:\learnnode\react\node_modules\express-react-views\node_modules\babel\node_modules\babel-core\lib\babel\api\register\node.js:158:7)
   at Module.load (module.js:355:32)
   at Function.Module._load (module.js:310:12)
   at Module.require (module.js:365:17)
   at require (module.js:384:17)
   at View.renderFile [as engine] (D:\learnnode\react\node_modules\express-react-views\index.js:37:23)
   at View.render (D:\learnnode\react\node_modules\express\lib\view.js:93:8)
```

But... the same thing happens if I copy-paste the program from exercise screen.
I'm currently using Windows 8.1, node v0.12.2, npm v2.7.4. Installed express, body-parser and express-react-views as recommended. Running from cmd.

Thanks in advance!

**Comment by rbusquet** [comment]
FYI, must be a windows thing, everything is fine using Linux.
Thanks, anyway :smile:

**Comment by martinheidegger** [comment]
ping @tako-black

**Comment by tako-black** [comment]
@rbusquet
I'm sorry I didn't test in Windows.
I'll fix that bug by tomorrow.

@martinheidegger
Thanks for your ping.

**Comment by martinheidegger** [comment]
@rbusquet Since there is now the issue open at learnyoureact https://github.com/tako-black/learnyoureact/issues/11 I will close this issue, cheers!

**Comment by rbusquet** [comment]
Thanks :)
