### ISSUE TITLE
javascripting: objects (lesson 15) throws node.js error

### ISSUE THREAD

**Issue by selfagency** [nodeschool/discussions#1195]
here's my code:

```
var pizza = {
  toppings: ['cheese', 'sauce', 'pepperoni'],
  crust: 'deep dish',
  serves: 2
}
console.log(pizza);
```

here's the error it throws:

```
selfagency@selfagency-macpro ~/C/javascripting> javascripting verify object.js 
{ [Error: Command failed: /bin/sh -c node "/Users/selfagency/Code/javascripting/object.js"
module.js:338
    throw err;
          ^
Error: Cannot find module '/Users/selfagency/Code/javascripting/object.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c node "/Users/selfagency/Code/javascripting/object.js"' }
```

**Comment by selfagency** [comment]
it was the file name. i'm an idiot.

**Comment by martinheidegger** [comment]
@selfagency You are not, everybody makes mistakes! Feel free to post again if you have an issue and good luck :+1:
