### ISSUE TITLE
Problem with solution with Brazilian language

### ISSUE THREAD

**Issue by edusantana** [nodeschool/discussions#1223]
I'm at **Make it Modular**

**program.js**
```
var mymodule = require('./mymodule.js')

mymodule(process.argv[2], process.argv[3], function printfiles(err, files){
  if (err != null){
    return console.error(err)
  } else {
    files.forEach(function (file){
      console.log(file)
    })
  }
})
```

**mymodule.js**:
```
var fs = require ('fs')
var path = require('path')

module.exports = function (directory, ext, callback){
  fs.readdir(directory, function listfiles(err, files){
    var list = null;
    if (err != null){
      return callback(err, list)
    }
    list = new Array();
    files.forEach(function (file){
      if (path.extname(file) === "." + ext){
        list.push(file)
      }
    })
    callback(null, list)
  })
}
```

When I run: 

```
$ learnyounode run program.js
CHANGELOG.md
LICENCE.md
README.md
```

After setting the language: `learnyounode -l pt-br`
```
$ learnyounode run program.js
CHANGELOG.md
LICENCE.md
README.md
```

But when I verify it:

```
$ learnyounode verify program.js

?exercises.MAKE IT MODULAR.compare.title || common.exercise.compare.title?

/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/comparestdout.js:19
  return new Array(sz + 1).join(ch)
         ^
RangeError: Invalid array length
    at repeat (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/comparestdout.js:19:10)
    at center (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/comparestdout.js:25:13)
    at Exercise.transform (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/comparestdout.js:57:40)
    at Transform._read (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Transform.Writable.write (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at Stream.ondata (stream.js:51:26)
    at Stream.emit (events.js:107:17)
santana@vaio-ubuntu14:~/w/nodejs/learning$ 
``` 

If I change the language to english (`learnyounode -l en`), it works:
```
$ learnyounode verify program.js

Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   "CHANGELOG.md"                      ==    "CHANGELOG.md"                     
   "LICENCE.md"                        ==    "LICENCE.md"                       
   "README.md"                         ==    "README.md"                        
   ""                                  ==    ""                                 

────────────────────────────────────────────────────────────────────────────────

✓ Submission results match expected
✓ Additional module file exports a single function
✓ Additional module file exports a function that takes 3 arguments
✓ Additional module file handles errors properly
✓ Additional module file handles callback argument
✓ Additional module file returned two arguments on the callback function
✓ Additional module file returned correct number of elements as the second argument of the callback
✓ Additional module file returned correct number of elements as the second argument of the callback
✓ Additional module file returned correct list of files as the second argument of the callback

# PASS
(....)
```

**Comment by SomeoneWeird** [comment]
I opened an issue over on the learnyounode repository, sorry for taking so long!

**Comment by edusantana** [comment]
Thanks @SomeoneWeird , should I close this one?

**Comment by SomeoneWeird** [comment]
Lets leave it open for a bit to see if anyone else has the same issue.

**Comment by SomeoneWeird** [comment]
Hey @edusantana, can you try the commands [here](https://github.com/workshopper/learnyounode/issues/318#issuecomment-116441996) and see if your problems goes away?

**Comment by edusantana** [comment]
@SomeoneWeird It's working now. Thanks :)
