### ISSUE TITLE
Issue with running javascripting tutorial

### ISSUE THREAD

**Issue by ajankelo** [nodeschool/discussions#1256]
Any ideas? Getting this error after selecting one of the menu options: 

/usr/local/lib/node_modules/javascripting/node_modules/workshopper-adventure/node_modules/simple-terminal-menu/simple-terminal-menu.js:80
    process.stdin.unpipe(menuStream)
                  ^
TypeError: Object #<ReadStream> has no method 'unpipe'
    at close (/usr/local/lib/node_modules/javascripting/node_modules/workshopper-adventure/node_modules/simple-terminal-menu/simple-terminal-menu.js:80:19)
    at Menu.menu.close (/usr/local/lib/node_modules/javascripting/node_modules/workshopper-adventure/node_modules/simple-terminal-menu/simple-terminal-menu.js:66:5)
    at Menu.EventEmitter.emit (events.js:115:20)
    at Menu.ondata [as _ondata] (/usr/local/lib/node_modules/javascripting/node_modules/workshopper-adventure/node_modules/terminal-menu/index.js:215:18)
    at DestroyableTransform._transform (/usr/local/lib/node_modules/javascripting/node_modules/workshopper-adventure/node_modules/terminal-menu/index.js:50:18)
    at DestroyableTransform.Transform._read (/usr/local/lib/node_modules/javascripting/node_modules/workshopper-adventure/node_modules/terminal-menu/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write

**Comment by SomeoneWeird** [comment]
What version of node do you have installed?

**Comment by ajankelo** [comment]
v0.8.7

**Comment by ajankelo** [comment]
Just fixed it by updating node, thanks for the help.

**Comment by SomeoneWeird** [comment]
Yeah, 0.8 is very old. Glad you got it working :)
