### ISSUE TITLE
Bug when I change lenguage 

### ISSUE THREAD

**Issue by jairorudas** [nodeschool/discussions#1320]
Hi! 
I speak Spanish and Portugues. When I like change languages on "learnyounode" for Spanish or Portugues always has Bug. Can you repair that? Thank you very much!!

**Comment by SomeoneWeird** [comment]
What's the issue?

**Comment by jairorudas** [comment]
Learnyounode has a Bug when change the language and run "hello world".

**Comment by SomeoneWeird** [comment]
What's the bug? It seems to be working OK for me

**Comment by jairorudas** [comment]
I have io.js and npm 2.13 and node 2.4. And the wrong is this:

TypeError: Cannot read property 'call' of undefined
    at emitNone (events.js:72:19)
    at Stream.emit (events.js:166:7)
    at Stream.Charm.end (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper/node_modules/terminal-menu/node_modules/charm/index.js:107:10)
    at Menu.close (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper/node_modules/terminal-menu/index.js:126:16)
    at Menu.<anonymous> (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper/menu.js:75:10)
    at emitTwo (events.js:92:20)
    at Menu.emit (events.js:172:7)
    at Menu.ondata [as _ondata] (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper/node_modules/terminal-menu/index.js:215:18)
    at DestroyableTransform._transform (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper/node_modules/terminal-menu/index.js:50:18)
    at DestroyableTransform.Transform._read (/usr/local/lib/node_modules/learnyounode/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/usr/local/lib/node_modules/learnyounode/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/usr/local/lib/node_modules/learnyounode/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)

**Comment by jairorudas** [comment]
I believe that the bug was repaired. Thanks a lot. (Y)
