### ISSUE TITLE
how-to-npm can't find package

### ISSUE THREAD

**Issue by Dynalt-glj1** [nodeschool/discussions#1378]
Steps to this point completed  successfully.

K:\Javascript\how-to-npm

> **npm dist-tag add my-test-proj@1.0.0 stable**
> npm ERR! Windows_NT 6.1.7601
> npm ERR! argv "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs
> \node_modules\npm\bin\npm-cli.js" "dist-tag" "add" "my-test-proj@1.0.0" "sta
> ble"
> npm ERR! node v0.12.7
> npm ERR! npm  v2.11.3
> npm ERR! code E404

npm **ERR! 404 missing : -/package/my-test-proj/dist-tags**

npm ERR! Please include the following file with any support request:
npm ERR!     K:\Javascript\how-to-npm\npm-debug.log

First, "~" isn't a directory in Windows. Where did the package path come from?
Second, where did I go wrong?
Third, how do I fix it?
## 

Thanks,

Garold L. Johnson

---

package.json

```
{
  "name": "my-test-proj",
  "version": "1.0.1",
  "description": "Just to get a project for the hpw-to-npm tutorial",
  "main": "index.js",
  "Dependencies": {},
  "devDependencies": {},
  "scripts": {
    "test": "node test.js"
  },
  "repository": {
    "type": "git",
    "url": "."
  },
  "keywords": [
    "test"
  ],
  "author": "Garold L. Johnson",
  "license": "ISC"
}
```

---

npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'dist-tag',
1 verbose cli   'add',
1 verbose cli   'my-test-proj@1.0.0',
1 verbose cli   'stable' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose dist-tag add stable to my-test-proj@1.0.0
5 silly mapToRegistry name my-test-proj
6 silly mapToRegistry using default registry
7 silly mapToRegistry registry http://localhost:15443/
8 silly mapToRegistry uri http://localhost:15443/my-test-proj
9 verbose request uri http://localhost:15443/-/package/my-test-proj/dist-tags
10 verbose request no auth needed
11 info attempt registry request try #1 at 5:11:28 PM
12 verbose request id 5a1c82efa5f76fbc
13 http request GET http://localhost:15443/-/package/my-test-proj/dist-tags
14 http 404 http://localhost:15443/-/package/my-test-proj/dist-tags
15 verbose headers { 'content-type': 'application/json',
15 verbose headers   date: 'Sun, 16 Aug 2015 00:11:28 GMT',
15 verbose headers   connection: 'keep-alive',
15 verbose headers   'transfer-encoding': 'chunked' }
16 verbose stack Error: missing : -/package/my-test-proj/dist-tags
16 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:247:14)
16 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:170:14)
16 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:354:22)
16 verbose stack     at Request.emit (events.js:110:17)
16 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1207:14)
16 verbose stack     at Request.emit (events.js:129:20)
16 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1153:12)
16 verbose stack     at IncomingMessage.emit (events.js:129:20)
16 verbose stack     at _stream_readable.js:908:16
16 verbose stack     at process._tickCallback (node.js:355:11)
17 verbose statusCode 404
18 verbose cwd K:\Javascript\how-to-npm
19 error Windows_NT 6.1.7601
20 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "dist-tag" "add" "my-test-proj@1.0.0" "stable"
21 error node v0.12.7
22 error npm  v2.11.3
23 error code E404
24 error 404 missing : -/package/my-test-proj/dist-tags
25 verbose exit [ 1, true ]
```

**Comment by pedesign** [comment]
Ongoing issue - same as https://github.com/nodeschool/discussions/issues/995
