### ISSUE TITLE
My First I/O

### ISSUE THREAD

**Issue by tech-boy** [nodeschool/discussions#1382]
My code

var fs = require('fs');
var z = fs.readFileSync('process.argv[2]');
var s=z.toString();
var a = s.split('\n');
var x = 0;
x = a.length - 1;
console.log(x);

Result in this error

fs.js:500
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'C:\Program Files (x86)\nodejs\process.argv[2]'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.(anonymous function) [as openSync] (C:\Users\Darshak\AppData\Roaming\npm\node_modules\learnyounode\exercises\my_first_io\wrap.js:30:19)
    at Object.fs.readFileSync (fs.js:352:15)
    at Object.fs.(anonymous function) [as readFileSync] (C:\Users\Darshak\AppData\Roaming\npm\node_modules\learnyounode\exercises\my_first_io\wrap.js:30:19)
    at Object.<anonymous> (C:\Program Files (x86)\nodejs\program.js:2:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by tech-boy** [comment]
It was Resolved. I had put quotes in the File Path.

Cheers!
