### ISSUE TITLE
'learnyounode' doesn't work giving strange error

### ISSUE THREAD

**Issue by VishalSubramanyam** [nodeschool/discussions#1465]
events.js:141
          throw er; // Unhandled 'error' event
          ^
    
    Error: write after end
        at writeAfterEnd     (C:\Users\VISHALSUBRAMANYAM\AppData\Roaming\npm\node_modules\learnyounode\node_mod    ules\through2\nod
    e_modules\readable-stream\lib\_stream_writable.js:144:12)
        at DestroyableTransform.Writable.write     (C:\Users\VISHALSUBRAMANYAM\AppData\Roaming\npm\node_modules\learnyounode\nod
    e_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:192:5)
        at Stream.ondata (stream.js:31:26)
        at emitOne (events.js:82:20)
        at Stream.emit (events.js:169:7)
        at Stream.Charm.write     (C:\Users\VISHALSUBRAMANYAM\AppData\Roaming\npm\node_modules\learnyounode\node_mod    ules\worksho
    pper\node_modules\terminal-menu\node_modules\charm\index.js:95:10)
        at Stream.Charm.position     (C:\Users\VISHALSUBRAMANYAM\AppData\Roaming\npm\node_modules\learnyounode\node_mod    ules\work
    shopper\node_modules\terminal-menu\node_modules\charm\index.js:134:14)
        at Menu.ondata [as _ondata]     (C:\Users\VISHALSUBRAMANYAM\AppData\Roaming\npm\node_modules\learnyounode\node_mod    ules\w
    orkshopper\node_modules\terminal-menu\index.js:213:24)
        at DestroyableTransform._transform     (C:\Users\VISHALSUBRAMANYAM\AppData\Roaming\npm\node_modules\learnyounode\node_mo
    dules\workshopper\node_modules\terminal-menu\index.js:50:18)
        at DestroyableTransform.Transform._read     (C:\Users\VISHALSUBRAMANYAM\AppData\Roaming\npm\node_modules\learnyounode\no
    de_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:184:10)
For some strange reason, I am not able to navigate around the menu.

**Comment by SomeoneWeird** [comment]
What version of node do you have installed?

**Comment by VishalSubramanyam** [comment]
I have 4.1.1

**Comment by VishalSubramanyam** [comment]
And this error occurs not only in learnyounode but also in all other workshoppers.

**Comment by SomeoneWeird** [comment]
#1448

**Comment by gaboesquivel** [comment]
HI @VishalSubramanyam, In the mean time you use https://github.com/coreybutler/nvm-windows to manage multiple node versions on your computer. Install 0.12 or io.js and run the workshops using that version, until #1448 is fixed in version 4

**Comment by SomeoneWeird** [comment]
This has been fixed upstream in node 5.1.0
