### ISSUE TITLE
Error in goingnative FOR THE SAKE OF ARGUMENT

### ISSUE THREAD

**Issue by richarddong** [nodeschool/discussions#1469]
Hello!

When I use `$ node-gyp rebuild` and `$ node index.js SOMETEXT` it's working, but when `$ goingnative verify myaddon` I get this:

```
✓ package.json contains `"gypfile": true`
✓ binding.gyp includes a "myaddon" target
✓ binding.gyp includes "myaddon.cc" as a source file
✓ binding.gyp includes a correct NAN include statement
  CXX(target) Release/obj.target/myaddon/myaddon.o
  SOLINK_MODULE(target) Release/myaddon.node
  SOLINK_MODULE(target) Release/myaddon.node: Finished
  CXX(target) Release/obj.target/myaddon/myaddon.o
  SOLINK_MODULE(target) Release/myaddon.node
  SOLINK_MODULE(target) Release/myaddon.node: Finished

/Users/develop/develop/nodeschool/~test-addon-faux.2945/index.js:6
addon.print(stringArg)
      ^
Error: Error converting first argument to string
    at Object.<anonymous> (/Users/develop/develop/nodeschool/~test-addon-faux.2945/index.js:6:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
FAUX
Could not verify: Command failed: 
/Users/develop/develop/nodeschool/~test-addon-faux.2945/index.js:6
addon.print(stringArg)
      ^
Error: Error converting first argument to string
    at Object.<anonymous> (/Users/develop/develop/nodeschool/~test-addon-faux.2945/index.js:6:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

`addon.cc`:

```
#include <nan.h>

using namespace v8;

NAN_METHOD(Print) {
	Nan::MaybeLocal<String> maybeStr = Nan::To<String>(info[0]);
	if (maybeStr.IsEmpty() == false) {
		Local<String> str = maybeStr.ToLocalChecked();
		printf("%s\n", *String::Utf8Value(str));
	}
}

NAN_MODULE_INIT(Init) {
  Nan::Set(target, Nan::New("print").ToLocalChecked(),
      Nan::GetFunction(Nan::New<FunctionTemplate>(Print)).ToLocalChecked());
}

NODE_MODULE(myaddon, Init)
```

`index.js`:

```
var bindings = require('bindings')
var addon = bindings('myaddon')

var stringArg = process.argv[2]

addon.print(stringArg)
```

Thank you!

**Comment by SomeoneWeird** [comment]
`ToLocalChecked` shouldn't be used in that case, did you get that from the `goingnative` docs? It was recently upgraded to Nan2 and may have outdated info somewhere.

Your best bet is to do something like this:

```c++
Nan::MaybeLocal<String> maybeStr = Nan::To<String>(info[0]);
Local<String> str;
if(maybeStr.ToLocal(&str) != true) {
  Nan::ThrowError("Error converting first argument to string");
}
printf("%s\n", *String::Utf8Value(str);
```

**Comment by richarddong** [comment]
yes it's from the cli docs. maybe the adventure should be updated somehow. :smile:
