### ISSUE TITLE
Workshops: Menu navigation does not work on Windows 10

### ISSUE THREAD

**Issue by Granjow** [nodeschool/discussions#1492]
No matter if I use the Node.js command prompt or cmd.exe or Git Bash or Cygwin, I cannot navigate in the node menus. The arrow keys do not change the selected entry, and after pressing some buttons and Enter, I get the error message below.

Can anybody reproduce this problem? How can it be fixed?

I'm on Node.js 4.2.0.

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (C:\Users\Simon\AppData\Roaming\npm\node_modules\learnyounode\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:144:12)
    at DestroyableTransform.Writable.write (C:\Users\Simon\AppData\Roaming\npm\node_modules\learnyounode\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:192:5)
    at Stream.ondata (stream.js:31:26)
    at emitOne (events.js:82:20)
    at Stream.emit (events.js:169:7)
    at Stream.Charm.write (C:\Users\Simon\AppData\Roaming\npm\node_modules\learnyounode\node_modules\workshopper\node_modules\terminal-menu\node_modules\charm\index.js:95:10)
    at Stream.Charm.reset (C:\Users\Simon\AppData\Roaming\npm\node_modules\learnyounode\node_modules\workshopper\node_modules\terminal-menu\node_modules\charm\index.js:111:10)
    at Menu.ondata [as _ondata] (C:\Users\Simon\AppData\Roaming\npm\node_modules\learnyounode\node_modules\workshopper\node_modules\terminal-menu\index.js:207:24)
    at DestroyableTransform._transform (C:\Users\Simon\AppData\Roaming\npm\node_modules\learnyounode\node_modules\workshopper\node_modules\terminal-menu\index.js:50:18)
    at DestroyableTransform.Transform._read (C:\Users\Simon\AppData\Roaming\npm\node_modules\learnyounode\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:184:10)
```

**Comment by SomeoneWeird** [comment]
#1448

**Comment by SomeoneWeird** [comment]
This has been fixed upstream in node 5.1.0

**Comment by 6pm** [comment]
not fixed. I use 5.8 version, menu doesn't work.

**Comment by lkurylo** [comment]
On v5.9.1 it doesn't work either
