### ISSUE TITLE
I can't make Filtered LS work

### ISSUE THREAD

**Issue by stevensgarcia** [nodeschool/discussions#1497]
Hello everyone,

I'm trying to solve the Filtered LS nodeschool exercise, but I got an error with __.extname()__ method. I don't understand why doesn't work, since I'm using the method correctly *"I think"*.

```javascript
// req module
var fs = require("fs");

/**
 * Read directory files
 * @param {array} process.argv[2] Directory path passed as an argument in CLI
 */
fs.readdir(process.argv[2], function(err, list) {
  // handle the error
  if (err) {
    console.log(err.message);
  }

  // add dot "." to the extension provided
  var filter = "." + process.argv[3];

  // print filtered file names
  for (var i = 0, len = list.length; i < len; i++) {

    if (process.argv[2].extname(list[i]) === filter) {
      console.log(list[i]);
    }

  }
});
```

This is the output using **$learnyounode verify ex5.js**

```
[Stevens@cli-sgarcia] learnyounode !142 $ learnyounode verify ex5.js 

/Applications/MAMP/htdocs/nodeschool/learnyounode/ex5.js:21
    if (process.argv[2].extname(list[i]) === filter) {
                        ^
TypeError: Object /var/folders/8_/zzb88fdd74q09mds5v8dgxv40000gn/T/_learnyounode_9621 has no method 'extname'
    at /Applications/MAMP/htdocs/nodeschool/learnyounode/ex5.js:21:25
    at Object.oncomplete (fs.js:108:15)

Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   ""                                  !=    "CHANGELOG.md"                     
                                       !=    "LICENCE.md"                       
                                       !=    "README.md"                        
                                       !=    ""                                 

────────────────────────────────────────────────────────────────────────────────

✗ Submission results did not match expected!
✓ Used asynchronous method: fs.readdir()

# FAIL
```

#### Versions:

* node 0.10.13
* npm 1.4.28
* nvm 0.25.1

**Thanks in advanced!**

**Comment by adobley** [comment]
.extname is a method on [path](https://nodejs.org/api/path.html).

Hopefully that points you in the right direction. If you still have trouble let me know.

**Comment by stevensgarcia** [comment]
@adobley Thank you very much. It works!

Solution was load the **path module;** and update the conditional with **"path"**

```javascript
var path = require("path");
```
```javascript
if (path.extname(list[i]) === filter) {
      console.log(list[i]);
    }
```
