### ISSUE TITLE
Arrays example

### ISSUE THREAD

**Issue by adelin2011** [nodeschool/discussions#1499]
The terminal is telling me that I have an error but I can't find anything wrong in my code: 
 var pizzaToppings = ['tomato sauce,''cheese,''pepperoni']; 
console.log(pizzaToppings);

**Comment by adobley** [comment]
It looks like you have the commas inside the quotes.

It should be something like ['foo', 'bar', 'example']. Everything inside a set of single quotes will be treated as a string and the , is the separator.

Let me know if that helps or not with resolving your issue.

**Comment by Hillsie** [comment]
I'd agree with your solution @adobley . At first I thought you had used a double quote, hence my next line. It's also interesting that node doesn't care if you use `'` or `"` , so much so that you can mix them up in the same array. The reason I know is because I just tested it out in the REPL. The only thing is really didn't like was if you mixed up ` 'tomato sauce" like that.
```
var pizzaToppings = ['tomato sauce', 'cheese', "pepperoni"]
undefined
console.log(pizzaToppings[0]);
tomato sauce
undefined
 console.log(pizzaToppings[1]);
cheese
undefined
console.log(pizzaToppings[2]);
pepperoni
undefined
var pizzaToppings = ['tomato sauce", 'cheese', "pepperoni']
SyntaxError: Unexpected identifier
    at Object.exports.createScript (vm.js:24:10)
    at REPLServer.defaultEval (repl.js:225:25)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:417:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
    at REPLServer.Interface._line (readline.js:550:8)
    at REPLServer.Interface._ttyWrite (readline.js:827:14)
```
