### ISSUE TITLE
npm install lololodash issue

### ISSUE THREAD

**Issue by ijones16** [nodeschool/discussions#1502]
Im getting and error after doing the following 
$ npm install -g lololodash
$ lololodash
Then I choose the first option >> 1: Getting Started

The error is: 

module.js:338
    throw err;
    ^

Error: Cannot find module 'workshopper/node_modules/colors-tmpl'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/lololodash/lib/verify.js:9:18)
    at Module._compile (module.js:434:26)
    at Module._extensions..js (module.js:452:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/lololodash/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

Im on node v4.0.0 and npm v3.3.8

**Comment by tako-black** [comment]
ping @mdunisch

**Comment by riyadhalnur** [comment]
one of the packages wan't installed. could you try running `npm install` again?

**Comment by soyginnie** [comment]
Go to lololodash path, maybe `node_modules/lololodash/` and ```$ npm install```

**Comment by mdunisch** [comment]
@ijones16, @tako-black: This error is fixed. Can you please install the latest version of lololodash and close this ticket if the error is fixed for you?

**Comment by tako-black** [comment]
@mdunisch Thanks!
I installed the latest version and checked the error have been fixed!

**Comment by SomeoneWeird** [comment]
:tada:
