### ISSUE TITLE
thinking-in-react install failed

### ISSUE THREAD

**Issue by nathan-bird** [nodeschool/discussions#1545]
[npm-debug.docx](https://github.com/nodeschool/discussions/files/37824/npm-debug.docx)

When trying to install thinking-in-react I get this error:

```
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:73:28)
npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:76:29)
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:84:16
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:82:15)
npm WARN addRemoteGit  git://github.com/rvagg/workshopper.git#cef8219ca2919964113c6daedd78a5db8404051b resetting remote C:\Users\Nathan\AppData\Roaming\npm-cache\_git-remotes\git-github-com-rvagg-workshopper-git-b7cda7ca because of error: { [Error: not found: git] code: 'ENOGIT' }
npm ERR! git clone --template=C:\Users\Nathan\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/rvagg/workshopper.git C:\Users\Nathan\AppData\Roaming\npm-cache\_git-remotes\git-github-com-rvagg-workshopper-git-b7cda7ca: undefined
npm ERR! git clone --template=C:\Users\Nathan\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/rvagg/workshopper.git C:\Users\Nathan\AppData\Roaming\npm-cache\_git-remotes\git-github-com-rvagg-workshopper-git-b7cda7ca: undefined
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "thinking-in-react"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Nathan\Documents\nodeSchool\thinking-in-react\npm-debug.log
```

Previous NodeSchool workshops (javascripting, learnyounode, learnyoureact) installed fine. Node v4.2.2 npm v2.14.7.

Any advise?

**Comment by SomeoneWeird** [comment]
You need to install git :)

**Comment by nathan-bird** [comment]
install git returns
'''
git@0.1.5 node_modules\git
└── mime@1.2.9
'''

**Comment by nathan-bird** [comment]
npm install -g git returns:
```
git@0.1.5 C:\Users\Nathan\AppData\Roaming\npm\node_modules\git
└── mime@1.2.9
```

**Comment by SomeoneWeird** [comment]
Try installing git from [here](http://git-scm.com/downloads) instead :) You only installed the node module

**Comment by nathan-bird** [comment]
That seems to have done the trick. Thank you
