### ISSUE TITLE
Cant run the workshops properly (I think it is tty related) on Git Bash

### ISSUE THREAD

**Issue by romantimm** [nodeschool/discussions#1582]
Hello! 

I've been trying to run the workshops on Git Bash (on my Windows machine) but the most of the workshops just don't work me. 

This is the error I get when I try to run scope-chaines-closures workshop: 

TypeError: process.stdin.setRawMode is not a function
    at module.exports (C:\Users\Roman\AppData\Roaming\npm\node_modules\scope-chains-closures\node_modules\adventure\lib\menu.js:51:19)
    at Shop.showMenu (C:\Users\Roman\AppData\Roaming\npm\node_modules\scope-chains-closures\node_modules\adventure\index.js:267:16)
    at Shop.execute (C:\Users\Roman\AppData\Roaming\npm\node_modules\scope-chains-closures\node_modules\adventure\index.js:131:14)
    at Object.<anonymous> (C:\Users\Roman\AppData\Roaming\npm\node_modules\scope-chains-closures\runner.js:26:6)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)

From the research I've done it seems that the solution might be in the shell that I run the workshop (something to do with tty). 

Thank you guys for the help and the incredible work you do! :D

**Comment by iUsemws** [comment]
same here, using Git Bash and ConEmu
