### ISSUE TITLE
Can't run git-it - Getting TypeError

### ISSUE THREAD

**Issue by ieromik** [nodeschool/discussions#1587]
When I enter "$ git-it" after installing, I receive the following block of text. Any help would be appreciated.

C:\Users\Owner\AppData\Roaming\npm\node_modules\git-it\node_modules\terminal-menu\index.js:59
    process.stdin.setRawMode(true);
                  ^

TypeError: process.stdin.setRawMode is not a function
    at new Menu (C:\Users\Owner\AppData\Roaming\npm\node_modules\git-it\node_modules\terminal-menu\index.js:59:19)
    at module.exports (C:\Users\Owner\AppData\Roaming\npm\node_modules\git-it\node_modules\terminal-menu\index.js:7:12)
    at showMenu (C:\Users\Owner\AppData\Roaming\npm\node_modules\git-it\node_modules\workshopper-jlord\menu.js:13:18)
    at Workshopper.printMenu (C:\Users\Owner\AppData\Roaming\npm\node_modules\git-it\node_modules\workshopper-jlord\workshopper.js:130:14)
    at Workshopper.init (C:\Users\Owner\AppData\Roaming\npm\node_modules\git-it\node_modules\workshopper-jlord\workshopper.js:97:8)
    at Object.<anonymous> (C:\Users\Owner\AppData\Roaming\npm\node_modules\git-it\git-it.js:17:4)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)

**Comment by noffle** [comment]
It sounds like terminal-menu isn't recognizing your terminal as a TTY. What OS are you running? What terminal emulator are you using, and what does `echo $TERM` output?

**Comment by ieromik** [comment]
Windows 7 Home Premium. Using Git Bash. $TERM outputs the following:
bash: TERM: command not found
Any ideas? I'm pretty new to this.

**Comment by chenvan** [comment]
see here https://github.com/senecajs/seneca-in-practice/issues/13
