### ISSUE TITLE
MAKE IT MODULAR (Exercise 6 of 13)  TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by Puine** [nodeschool/discussions#1606]
Hi,
Here is my code : 
program.js :
```javascript
 var filterMod = require('./module.js');
 var filePath  = process.argv[2];
 var extStr = process.argv[3];

 filterMod(filePath, extStr, function(err, data){
    if(err){
        console.log("ERROR");
    }
    else{
        console.log(data);
    }
 });
```

module.js : 

```javascript
var fs = require('fs');

module.exports = function (filePath, extStr, callback){
    fs.readdir(filePath, function (err, list){
        if(err){
            return callback(err);
        }
        else{
           for(var i = 0; i < list.length; i++){
                    var ext = "."+extStr;
                    if(list[i].substr(-1*ext.length,ext.length) === ext){
                        callback(null, list[i]);
                    }        
                }
        }
    });
}
```

and here is the answer I get when typing :  learnyounode verify program.js

```javascript
Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   "CHANGELOG.md"                      ==    "CHANGELOG.md"                     
   "LICENCE.md"                        ==    "LICENCE.md"                       
   "README.md"                         ==    "README.md"                        
   ""                                  ==    ""                                 

────────────────────────────────────────────────────────────────────────────────

/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:182
    processors[i].call(self, mode, function (err, pass) {
                 ^

TypeError: Cannot read property 'call' of undefined
    at next (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:182:18)
    at /home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:189:7
    at callback (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:26:15)
    at modFileError (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:31:5)
    at /home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:119:18
    at /home/ubuntu/workspace/module.js:12:25
    at FSReqWrap.oncomplete (fs.js:82:15)
```

So my answers seems right but I don't understand what's the problem... Anyone ?
Thanks !

**Comment by GiannisGl** [comment]
I think the problem is that it expected that you call the callback function #once# with an array of the filtered list, and not every time for a filtered file. The verify program seems to try to use the data variable as an array and there the problem happens. Try to modify your code, so that you store all the filtered files in an array, then call the callback function with that array and the callback function should print an array. Hope I helped!

**Comment by Puine** [comment]
It worked ! Thank you very much !

**Comment by davidlin504** [comment]
I use the array.push() method and rewrite the statement 

it works 

program.js

  if(err){
        console.log("ERROR");
    }
    else{
        data.forEach(function (d)
             {
                 console.log(d.toString());
             });
    }



module.js

if(err){
            return callback(err);
        }
        else{
            var elements = [];
  for(var i = 0; i < list.length; i++){
                    var ext = "."+extStr;
                    if(list[i].substr(-1*ext.length,ext.length) === ext){
                        elements.push(list[i]);
                    }        
                }
                callback(null, elements); 
        }

**Comment by PokimLee** [comment]
@GiannisGl thx,you save my time!

**Comment by SomeoneWeird** [comment]
If anyone else needs help, please open another issue :tada:
