### ISSUE TITLE
learnyounode 6:make  it module

### ISSUE THREAD

**Issue by liuestc** [nodeschool/discussions#1610]
my code:
main.js
```js
var mymodule=require("./mymodule");
mymodule(process.argv[2],process.argv[3],function(error,data){
if(error){
console.log(error);
}else{

console.log(item); 

}
});
```

mymodule.js
```js
var path=require("path");
var fs=require("fs")
;
module.export=function(dir,ext,callback){
 fs.readdir(dir,function(err,file){
		if(err){
			callback(err);
		}
		console.log(file)
	})
 
 new_file=file.filter(function(item){
  	if(item.extname(ext)="."+ext)
  		return item;
  })
 return callback(null,new_file)
}
```

```
mymodule(process.argv[2],process.argv[3],function(error,data){
^

TypeError: mymodule is not a function
    at Object.<anonymous> (C:\Users\jundongl\learnnode\main.js:13:1)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3
```

How to solve 
thanks

**Comment by finnp** [comment]
You have a typo. It is `module.exports` with an `s` in mymodule.js :relaxed:

**Comment by titoesteves** [comment]
Also you have the semicolon after `require('fs')` on a separate line.

**Comment by aloisdg** [comment]
By the way, you should decide if you want to use semicolon or not. Coherence in code is a quality.
