### ISSUE TITLE
Unable to verify git-it workshop module 

### ISSUE THREAD

**Issue by anvis2000** [nodeschool/discussions#1642]
I've completed all of the requirements for the 3rd module in the git-it workshop.  When I attempt to verify my work (using 'git-it verify') I get the following error:
C:\Users\Annamalai\Documents\GitHub> git-it verify
module.js:341
    throw err;
    ^

Error: Cannot find module 'C:\Users\Annamalai\AppData\Roaming\npm\node_modules\git-it\problems/setup.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Workshopper.verify (C:\Users\Annamalai\AppData\Roaming\npm\node_modules\git-it\node_modules\workshopper-jlord\workshopper.js:112:13)
    at Workshopper.init (C:\Users\Annamalai\AppData\Roaming\npm\node_modules\git-it\node_modules\workshopper-jlord\workshopper.js:95:17)
    at Object.<anonymous> (C:\Users\Annamalai\AppData\Roaming\npm\node_modules\git-it\git-it.js:17:4)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
 C:\Users\Annamalai\Documents\GitHub>

This is on Windows 10.  Any ideas?  Is this a bug or a problem with my setup?

**Comment by SomeoneWeird** [comment]
Looks like git-it might be hardcoding a path, and not using `path.resolve` to make sure it's compatible on windows too.

**Comment by koddsson** [comment]
@anvis2000 could you run `git-it --version` in a terminal for me and post the results here?

**Comment by anvis2000** [comment]
C:\Users\Annamalai>git-it --version
git-it@1.6.9
