### ISSUE TITLE
es6-promise error

### ISSUE THREAD

**Issue by agatsoh** [nodeschool/discussions#1644]
- node version: <v4.2.6>
- npm version:  <2.14.12>
### Error output

```
 krishna@Krishna:~/learningnode/promises$ promise-it-wont-hurt run fulfill.js 
/home/krishna/learningnode/promises/node_modules/es6-promise/dist/es6-promise.js:930
      if (P && Object.prototype.toString.call(P.resolve()) === '[object Promise]' && !P.cast) {
                                                ^

TypeError: P.resolve is not a function
    at lib$es6$promise$polyfill$$polyfill (/home/krishna/learningnode/promises/node_modules/es6-promise/dist/es6-promise.js:930:49)
    at Object.<anonymous> (/home/krishna/learningnode/promises/node_modules/es6-promise/dist/es6-promise.js:952:5)
    at Object.<anonymous> (/home/krishna/learningnode/promises/node_modules/es6-promise/dist/es6-promise.js:953:4)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/krishna/learningnode/promises/fulfill.js:1:77)
```
### My Code

``` js
 var Promise = require('es6-promise');

var promise = new Promise(function(fulfill,reject){
    setTimeout(function(){
    fulfill("FULFILLED!");
    },300);
});

promise.then(function(value){
    console.log(value);
});
```

**Comment by agatsoh** [comment]
The same thing with a bluebird promise runs fine but es6 promise gives an error.

**Comment by aliok** [comment]
Get rid of ` var Promise = require('es6-promise');`

See https://github.com/stevekane/promise-it-wont-hurt/issues/68

**Comment by leicj** [comment]
my code is:
```
'use strict';

var promise = new Promise(function(fulfill, reject) {
  setTimeout(function() {
    fulfill('FULFILLED!');
  }, 300);
}).then(function(fulfill, reject) {
  console.log(fulfill);
});
```

using then after the new Promise.
