### ISSUE TITLE
#6 Makeitmodular: correct results AND throwing error at the same time?

### ISSUE THREAD

**Issue by ostigley** [nodeschool/discussions#1645]
* node version: 4.3.0
* npm version:  2.14.12

I seem to be receiving a learnyounode system error, but still printing out the correct results.  Can someone please confirm my code is worthy?

thanks

### Error output
```
 `Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   "CHANGELOG.md"                      ==    "CHANGELOG.md"                     
   "LICENCE.md"                        ==    "LICENCE.md"                       
   "README.md"                         ==    "README.md"                        
   ""                                  ==    ""                                 

────────────────────────────────────────────────────────────────────────────────

/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:182
    processors[i].call(self, mode, function (err, pass) {
                 ^

TypeError: Cannot read property 'call' of undefined
    at next (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:182:18)
    at /usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:189:7
    at callback (/usr/local/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:26:15)
    at modFileError (/usr/local/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:31:5)
    at /usr/local/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:119:18
    at /Users/Olly/workspace/learnyounode/mymodule.js:13:13
    at Array.forEach (native)
    at /Users/Olly/workspace/learnyounode/mymodule.js:11:9
    at FSReqWrap.oncomplete (fs.js:82:15)
`
```

### My Code: makeitmodular.js
```js

var dir = process.argv[2];
var filter = process.argv[3];
var mymodule = require('./mymodule.js')


mymodule (dir,filter, function (err, data) {
	if (err) {
		console.log("There was an error")
	}
	else {
		console.log(data)
	}
})
```

### My Code: mymodule.js
```js
var fs = require('fs')
var path = require('path');

module.exports = function(dir, filter, callback) {

	fs.readdir(dir, function (err, list) {
		if (err) {
			return callback(err)
		}
		else {
			list.forEach( function(file) {
				if ( path.extname(file) === '.' + filter ) {
					return callback(null,file)
				}
			})
		}
	})

};

```

**Comment by GiannisGl** [comment]
see #1606

**Comment by ostigley** [comment]
@GiannisGl thank you, same problem same solution, just couldn't find it before posting.
