### ISSUE TITLE
learnyoureact - problem 1 (HELLO_REACT)

### ISSUE THREAD

**Issue by brunobely** [nodeschool/discussions#1647]
- node version: v5.6.0
- npm version: 3.7.2
### Error output

```
SyntaxError: /Users/[myusername]/Copy/NodeSchool/learnyoureact/project/views/index.jsx: Unexpected token (5:9)
  3 | export default class TodoBox extends React.Component{
  4 |   render() {
> 5 |       return <div className="todoBox">
    |          ^
  6 |           Hello, world!
  7 |           </div>
  8 |   }
    at Parser.pp.raise (/Users/[myusername]/Copy/NodeSchool/learnyoureact/project/node_modules/babylon/index.js:1425:13)
    at Parser.pp.unexpected (/Users/[myusername]/Copy/NodeSchool/learnyoureact/project/node_modules/babylon/index.js:2905:8)
    at Parser.pp.parseExprAtom (/Users/[myusername]/Copy/NodeSchool/learnyoureact/project/node_modules/babylon/index.js:754:12)
    at Parser.pp.parseExprSubscripts (/Users/[myusername]/Copy/NodeSchool/learnyoureact/project/node_modules/babylon/index.js:509:19)
    at Parser.pp.parseMaybeUnary (/Users/[myusername]/Copy/NodeSchool/learnyoureact/project/node_modules/babylon/index.js:489:19)
    at Parser.pp.parseExprOps (/Users/[myusername]/Copy/NodeSchool/learnyoureact/project/node_modules/babylon/index.js:420:19)
    at Parser.pp.parseMaybeConditional (/Users/[myusername]/Copy/NodeSchool/learnyoureact/project/node_modules/babylon/index.js:402:19)
    at Parser.pp.parseMaybeAssign (/Users/[myusername]/Copy/NodeSchool/learnyoureact/project/node_modules/babylon/index.js:365:19)
    at Parser.pp.parseExpression (/Users/[myusername]/Copy/NodeSchool/learnyoureact/project/node_modules/babylon/index.js:329:19)
    at Parser.pp.parseReturnStatement (/Users/[myusername]/Copy/NodeSchool/learnyoureact/project/node_modules/babylon/index.js:2106:26)
```
### My Code

program.js code:

``` js
var path = require('path')
var express = require('express')
var app = express()

app.set('port', (process.argv[2] || 3000))
app.set('view engine', 'jsx')
app.set('views', path.join(__dirname, '/views'))
app.engine('jsx', require('express-react-views')
    .createEngine({ transformViews: false}))

require('babel-core/register')({
    ignore: false
})

app.use('/', function (req, res) {
    res.render('index', '')
})

app.listen(app.get('port'), function () {})
```

index.jsx code:

``` js
import React from 'react';

export default class TodoBox extends React.Component{
    render() {
        return <div className="todoBox">
            Hello, world!
            </div>
    }
}
```

**Comment by brunobely** [comment]
After installing babel-preset-es2015, babel-preset-react, and adding both to my package.json Babel presets, the error has changed to:

```
TypeError: require(...) is not a function
   at exports.default (index.js:12:17)
   at Function.memoisePluginContainer (/Users/brunoely/Copy/NodeSchool/learnyoureact/secondproject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:136:13)
   at Function.normalisePlugin (/Users/brunoely/Copy/NodeSchool/learnyoureact/secondproject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:170:32)
   at /Users/brunoely/Copy/NodeSchool/learnyoureact/secondproject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:210:30
   at Array.map (native)
   at Function.normalisePlugins (/Users/brunoely/Copy/NodeSchool/learnyoureact/secondproject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:182:20)
   at OptionManager.mergeOptions (/Users/brunoely/Copy/NodeSchool/learnyoureact/secondproject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:298:36)
   at /Users/brunoely/Copy/NodeSchool/learnyoureact/secondproject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:370:14
   at /Users/brunoely/Copy/NodeSchool/learnyoureact/secondproject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:390:24
   at Array.map (native)
```

**Comment by tgfjt** [comment]
@kohei-takata could you help :bow:

**Comment by kohei-takata** [comment]
@brunobely 
Which version of Babel do you use?

**Comment by OLI9292** [comment]
Remove { transformViews: false }, and it should work.
