### ISSUE TITLE
Question regarding the learnyounode Filtered LS module

### ISSUE THREAD

**Issue by anvis2000** [nodeschool/discussions#1651]
I'm having trouble understanding what the Filtered LS module in the learnyounode tutorial is asking for.  

I set var p = process.argv[2] in the code below and that simply returns all the file folders under the root (Windows) directory.  Can someone help me understand what is being passed to my code when I try to verify my solution?

 
* node version: 4.3.1
* npm version:  2.14.12

### Error output
```
C:\Users\Annamalai\nodeschool\learnyounode>learnyounode verify file-list.js
fs.js:803
  binding.readdir(pathModule._makeLong(path), req);
          ^

TypeError: path must be a string
    at TypeError (native)
    at Object.fs.readdir (fs.js:803:11)
    at Object.fs.(anonymous function) [as readdir] (C:\Users\Annamalai\AppData\Roaming\npm\node_modules\learnyounode\exercises\my_first_io\wrap.js:30:19)
    at Object.<anonymous> (C:\Users\Annamalai\nodeschool\learnyounode\file-list.js:5:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED
────────────────────────────────────────────────────────────────────────────────

   ""                                  !=    "CHANGELOG.md"
                                       !=    "LICENCE.md"
                                       !=    "README.md"
                                       !=    ""

────────────────────────────────────────────────────────────────────────────────

  ✗  Submission results did not match expected!

  ✓  Used asynchronous method: fs.readdir()


     # FAIL
```

### My Code
```js
var fs = require("fs"),
    path = require("path");

var p;
fs.readdir(p, function (err, files) {
    if (err) {
        throw err;
    }

    files.map(function (file) {
        return path.join(p, file);
    }).filter(function (file) {
        return fs.statSync(file).isFile();
    }).forEach(function (file) {
        console.log("%s (%s)", file, path.extname(file));
    });
});
```

**Comment by ghufransyed** [comment]
I think your fourth line should be:
`var p = process.argv[2]`

You said you did that in your description, but it's not in the code you showed for some reason.

If you want to see what is being passed to your code, just add `console.log(variablename);` . You'll need to remove it before the final tests will pass, but it can be helpful when figuring out what's going on.

**Comment by anvis2000** [comment]
Thank you.  I did in fact have the process.argv[2] assigned to var p.  What I was missing was the process.argv[3].  Works now.  Thanks for your help.
