### ISSUE TITLE
Filtered LS issue- path.extname throwing error

### ISSUE THREAD

**Issue by arindam-chattopadhya** [nodeschool/discussions#1654]
* node version: 4.3.2.
* npm version:  2.14.12
### Error output
```
 // copy your error output here
E:\myStuff\Coding\Node.js\workshopper>learnyounode run FilteredLS.js
E:\myStuff\Coding\Node.js\workshopper\FilteredLS.js:29
    if (path.extname(filename) === fileExtension) {
             ^
TypeError: path.extname is not a function
    at E:\myStuff\Coding\Node.js\workshopper\FilteredLS.js:29:14
    at Array.forEach (native)
    at E:\myStuff\Coding\Node.js\workshopper\FilteredLS.js:28:7
    at FSReqWrap.oncomplete (fs.js:82:15)
```

### My Code
```js
 // copy your code here
var fs = require ('fs'); 
var path = require ('path')
var path = process.argv[2] 
var extn = process.argv[3] 
fs.readdir(path, function(err,list){
	list.forEach(function(filename){
    if (path.extname(filename) === fileExtension) {
      console.log(filename);
    }
  });
});
```

**Comment by maxrimue** [comment]
This fails because first, you use the `path` variable for importing the `path`-module, but then overwrite that variable using `process.argv[2]`. You could rename the second `path` to something like `filePath`, with this code:
```javascript
var fs = require ('fs'); 
var path = require ('path');
var filePath = process.argv[2]; // Don't use 'path' twice
var extn = process.argv[3];
fs.readdir(filePath, function(err,list){ // Rename 'path' to 'filePath' here too
    list.forEach(function(filename){
    if (path.extname(filename) === fileExtension) {
      console.log(filename);
    }
  });
});
```

**Comment by arindam-chattopadhya** [comment]
That worked thanks a lot...
