### ISSUE TITLE
Having issue with "My First Async IO"

### ISSUE THREAD

**Issue by jpjananraja** [nodeschool/discussions#1671]
- node version: v4.4.0
- npm version:  v4.4.0
### Error output

```
 // copy your error output here
fs.js:250
  binding.open(pathModule._makeLong(path),
          ^

TypeError: path must be a string
    at TypeError (native)
    at Object.fs.readFile (fs.js:250:11)
    at Object.<anonymous> (/Users/jananrajaratnam/Documents/node-react-master/learnyounode/fsasync.js:5:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```
### My Code

``` js
 // copy your code here
var fs = require("fs");



var buffObj = fs.readFile(process.argv[2], "utf-8", function(err, data)
{
    if(err){
        console.log("error found")
    }
    else
    {
        console.log(data);
        return data;
    }

});

console.log("buuf is " + buffObj);

var strBuffObj = buffObj.toString();

var arr = strBuffObj.split("\n");


var count = arr.length -1;

console.log(count);
```

**Comment by noffle** [comment]
There are a few things going on here. Some questions to get you thinking about your code:

1. How are you running `fsasync.js`? As `node fsasync.js`? As `learnyounode verify fsasync.js`?
2. What is `process.argv[2]`? How does it get its value?
3. Look at the documentation for [fs.readFile()](https://nodejs.org/api/fs.html#fs_fs_readfile_file_options_callback). Does it have a return value? How does it communicate its result?
4. What value do you expect `buffObj` to have under your call to `fs.readFile()`? What is it when you run it?
