### ISSUE TITLE
learnyounode doesn't verify any exercise

### ISSUE THREAD

**Issue by andreavigani** [nodeschool/discussions#1700]
* node version: v4.4.2
* npm version:  2.15.0

### Error output
C:\Users\Andrea\nodeschool\learnyounode>learnyounode verify program.js

?exercises.BABY STEPS.compare.title || common.exercise.compare.title || compare.title?

C:\Users\Andrea\AppData\Roaming\npm\node_modules\learnyounode\node_modules\workshopper-exercise\comparestdout.js:19
  return new Array(sz + 1).join(ch)
         ^

RangeError: Invalid array length
    at repeat (C:\Users\Andrea\AppData\Roaming\npm\node_modules\learnyounode\node_modules\workshopper-exercise\comparestdout.js:19:10)
    at center (C:\Users\Andrea\AppData\Roaming\npm\node_modules\learnyounode\node_modules\workshopper-exercise\comparestdout.js:25:13)
    at Exercise.transform (C:\Users\Andrea\AppData\Roaming\npm\node_modules\learnyounode\node_modules\workshopper-exercise\comparestdout.js:57:40)
    at DestroyableTransform.Transform._read (C:\Users\Andrea\AppData\Roaming\npm\node_modules\learnyounode\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (C:\Users\Andrea\AppData\Roaming\npm\node_modules\learnyounode\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:147:83)
    at doWrite (C:\Users\Andrea\AppData\Roaming\npm\node_modules\learnyounode\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:313:64)
    at writeOrBuffer (C:\Users\Andrea\AppData\Roaming\npm\node_modules\learnyounode\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (C:\Users\Andrea\AppData\Roaming\npm\node_modules\learnyounode\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:241:11)
    at Stream.ondata (stream.js:31:26)
    at emitOne (events.js:77:13)

### My Code
var sum = 0;
for (var i = 2; i < process.argv.length; i++) {
    sum += (+process.argv[i]);
}
console.log(sum);

**Comment by andreavigani** [comment]
Solved changing language from Italian to English.
