### ISSUE TITLE
learnyounode error?

### ISSUE THREAD

**Issue by Dark-Omega** [nodeschool/discussions#1709]
Hi, when i try to verify programs of learnyounode, i get always the same error
- node version: v4.4.3
- npm version:  2.15.1
### Error output

C:\Users\myUser\Documents\myUser\node.js\learnyounode>learnyounode verify program.js

?exercises.BABY STEPS.compare.title || common.exercise.compare.title || compare.title?

C:\Users\myUser\AppData\Roaming\npm\node_modules\learnyounode\node_modules\workshopper-exercise\comparestdout.js:19
  return new Array(sz + 1).join(ch)
         ^

RangeError: Invalid array length
    at repeat (C:\Users\myUser\AppData\Roaming\npm\node_modules\learnyounode\node_modules\workshopper-exercise\comparestdout.js:19:10)
    at center (C:\Users\myUser\AppData\Roaming\npm\node_modules\learnyounode\node_modules\workshopper-exercise\comparestdout.js:25:13)
    at Exercise.transform (C:\Users\myUser\AppData\Roaming\npm\node_modules\learnyounode\node_modules\workshopper-exercise\comparestdout.js:57:40)
    at DestroyableTransform.Transform._read (C:\Users\myUser\AppData\Roaming\npm\node_modules\learnyounode\node_modules\through2\node_modules\readable-stream\lib_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (C:\Users\myUser\AppData\Roaming\npm\node_modules\learnyounode\node_modules\through2\node_modules\readable-stream\lib_stream_transform.js:147:83)
    at doWrite (C:\Users\myUser\AppData\Roaming\npm\node_modules\learnyounode\node_modules\through2\node_modules\readable-stream\lib_stream_writable.js:313:64)
    at writeOrBuffer (C:\Users\myUser\AppData\Roaming\npm\node_modules\learnyounode\node_modules\through2\node_modules\readable-stream\lib_stream_writable.js:30
2:5)
    at DestroyableTransform.Writable.write (C:\Users\myUser\AppData\Roaming\npm\node_modules\learnyounode\node_modules\through2\node_modules\readable-stream\lib_stream_writable.js:241:11)
    at Stream.ondata (stream.js:31:26)
    at emitOne (events.js:77:13)
### My Code

console.log(Number(process.argv[2])+Number(process.argv[3])+Number(process.argv[4]));

help please :\

**Comment by cristianhosu** [comment]
Have you tried instead of assuming that you have only 3 numbers to add, to loop through the process.argv array and sum the values?

try` console.log(process.argv.length)`
and use learnyounode run to see what happens.
