### ISSUE TITLE
Error running thinking-in-react 

### ISSUE THREAD

**Issue by jjsub** [nodeschool/discussions#1711]
- node version: <run "node -v" in you terminal and replace this>
- npm version:  <run "npm -v" in you terminal and replace this>
### Error output

```
Error: Cannot find module '/Users/nss/Documents/code/thinking-in-react/node_modules/react-dom'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/thinking-in-react/exercises/spec_2_1.js:1:78)
    at Module._compile (module.js:413:34)
    at Module._extensions..js (module.js:422:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/thinking-in-react/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```
### My Code

``` js
 // copy your code here
```

**Comment by koddsson** [comment]
Hey @jjsub!

Did you remember to install the required packages for this exercise?

```
You are going to need reactjs for this exercise. Install it using npm.

    $ npm install react@0.14.0-rc1 react-dom@0.14.0-rc1
```
