### ISSUE TITLE
[Scope Chains]:

### ISSUE THREAD

**Issue by andreos1988** [nodeschool/discussions#1722]
* node version: <4.4.3>
* npm version:  <2.15.1>

### Error output
```
$ scope-chains-closures
C:\Users\Andre\AppData\Roaming\npm\node_modules\scope-chains-closures\node_modules\adventure\lib\menu.js:51
    process.stdin.setRawMode(true);
                  ^

TypeError: process.stdin.setRawMode is not a function
    at module.exports (C:\Users\Andre\AppData\Roaming\npm\node_modules\scope-chains-closures\node_modules\adventure\lib\menu.js:51:19)
    at Shop.showMenu (C:\Users\Andre\AppData\Roaming\npm\node_modules\scope-chains-closures\node_modules\adventure\index.js:267:16)
    at Shop.execute (C:\Users\Andre\AppData\Roaming\npm\node_modules\scope-chains-closures\node_modules\adventure\index.js:131:14)
    at Object.<anonymous> (C:\Users\Andre\AppData\Roaming\npm\node_modules\scope-chains-closures\runner.js:26:6)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)

```

### My Code
```js
 // copy your code here
```

**Comment by riyadhalnur** [comment]
The error is clearly mentioned in the error message. There's no `setRawMode` function on `process.stdin`.

**Comment by SomeoneWeird** [comment]
@riyadhalnur yes, but the error is clearly inside of scope-chains/adventure. Don't need to be rude about it

**Comment by SomeoneWeird** [comment]
Oops.

**Comment by riyadhalnur** [comment]
@SomeoneWeird I wasn't being rude. Sorry if the language comes off as that.

**Comment by riyadhalnur** [comment]
@andreos1988 This seems to be a problem for many on Windows 10. An issue has been filed here https://github.com/jesstelford/scope-chains-closures/issues/15

**Comment by andreos1988** [comment]
@riyadhalnur @SomeoneWeird I undestood the problem thanks guys :+1:
