### ISSUE TITLE
learnyounode - Make it Modular - TypeError

### ISSUE THREAD

**Issue by jhuynh85** [nodeschool/discussions#1785]
Hi all, when I run `learnyounode verify program.js` for exercise 6 I get the following:

```
Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   "CHANGELOG.md"                      ==    "CHANGELOG.md"                     
   "LICENCE.md"                        ==    "LICENCE.md"                       
   "README.md"                         ==    "README.md"                        
   ""                                  ==    ""                                 

────────────────────────────────────────────────────────────────────────────────

/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:188
    processors[i].call(self, mode, function (err, pass) {
                 ^

TypeError: Cannot read property 'call' of undefined
    at next (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:188:18)
    at /home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:195:7
    at callback (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:26:15)
    at modFileError (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:31:5)
    at /home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:119:18
    at /home/ubuntu/workspace/ex6-filtered-module.js:13:17
    at Array.forEach (native)
    at /home/ubuntu/workspace/ex6-filtered-module.js:11:17
    at FSReqWrap.oncomplete (fs.js:82:15)
```
For reference, my files are:

**program.js**
```
var fm = require('./ex6-filtered-module.js');

fm(process.argv[2], process.argv[3], function(err, data){
   if (!err){
       console.log(data);
   } else {
       console.log(err);
   }
});
```
**ex6-filtered-module.js**
```
var fs = require('fs');
var path = require('path');

module.exports = function(pa, ext, callback){
    ext = '.'+ext;
    fs.readdir(pa, function(err, fileStr){
        if (err){
            return callback(err);
        }
        
        fileStr.forEach(function(file){
            if (path.extname(file)==ext){
                callback(null,file);
            }
        });
    });
};
```

node v4.4.5
learnyounode v3.5.3

Any help would be appreciated, thanks.

**Comment by jhuynh85** [comment]
Same issue as #1606
