### ISSUE TITLE
Javascripting - error in 'if-statement' lesson

### ISSUE THREAD

**Issue by ricardogouveia3** [nodeschool/discussions#1789]
* node version: v0.12.7
* npm version:  2.14.2

### Error output
```
 { [Error: Command failed: /bin/sh -c node "/Users/ricardogouveia3/Dev/inlearning-code/nodejs/javascripting/if-statement.js"
/Users/ricardogouveia3/Dev/inlearning-code/nodejs/javascripting/if-statement.js:2
if (fruit.length() > 5) {
          ^
TypeError: number is not a function
    at Object.<anonymous> (/Users/ricardogouveia3/Dev/inlearning-code/nodejs/javascripting/if-statement.js:2:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c node "/Users/ricardogouveia3/Dev/inlearning-code/nodejs/javascripting/if-statement.js"' }
```

### My Code
```js
var fruit = 'orange';
if (fruit.length() > 5) {
  console.log('The fruit has more than five characters')
}
else {
  console.log('The fruit has five characters or less')
};
```

**Comment by maxrimue** [comment]
The issue here is caused by the way you reference the length of `fruit` in this line:
```javascript
if (fruit.length() > 5) {
```

If you reference it like `fruit.length()` you call the function `length` of `fruit`, but `length` is not a function you could call, it's a simple value, which is why you need to reference it like `fruit.length` instead.

Every time you want to reference the result of a function, add a `()` after it (which requires that the value points to a function), for referencing the property itself, don't add `()`.

**Comment by ricardogouveia3** [comment]
Thanks! @maxrimue
