### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:80 - Learnyounode Exercise 7

### ISSUE THREAD

**Issue by gmurop** [nodeschool/discussions#1806]
* node version: v6.3.0
* npm version:  v6.3.0

### Error output
```
{ Error: connect ECONNREFUSED 127.0.0.1:80
    at Object.exports._errnoException (util.js:1008:11)
    at exports._exceptionWithHostPort (util.js:1031:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 80 }
[gmurop@localhost nodeschool]$ learnyounode verify ejercicio7.js 
{ Error: connect ECONNREFUSED 127.0.0.1:80
    at Object.exports._errnoException (util.js:1008:11)
    at exports._exceptionWithHostPort (util.js:1031:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 80 }
```

### My Code
```js
var http = require('http');

var url = process.argv[3];

var res = http.get(url, function (response) {

	console.log(response.setEncoding('utf8'));

});

res.on('error', function (err) {
	console.error(err);
});
```

Somebody can help me? I am using Arch Linux on Virtualbox.

**Comment by gmurop** [comment]
Sorry! I'm an idiot, I was getting the wrong param (agv[3]) instead of argv[2])

**Comment by xtuc** [comment]
Ports below 1024 require special permissions to be able to run. I recommend you using an other port, 8080 for example.
