### ISSUE TITLE
Please Help , Getting correct number of lines but still failing with  "My First I/O"

### ISSUE THREAD

**Issue by woodyb23** [nodeschool/discussions#1825]
I am getting the right number of lines but my code is still failing.

* node version: 4.4.5
* npm version:  2.15.5

### Error output
woodyb23:~/workspace $ learnyounode verify learnyounode/program.js

fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'program.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.(anonymous function) [as openSync] (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/learnyounode/exercises/my_first_io/wrap.js:30:19)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.(anonymous function) [as readFileSync] (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/learnyounode/exercises/my_first_io/wrap.js:30:19)
    at Object.<anonymous> (/home/ubuntu/workspace/learnyounode/program.js:2:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

Your submission results compared to the expected:
### My Code
 var fs = require('fs') ;
 var buf = fs.readFileSync('program.js').toString();
 var newLines = buf.split('\n');
 console.log(newLines.length);

**Comment by edwinharly** [comment]
Try this : 
```
console.log(newLines.length - 1);
```

**Comment by woodyb23** [comment]
@edwinharly  Thank you so much for your help! 

Upon trying your suggest I get the same error

**Comment by edwinharly** [comment]
@woodyb23 I think I got it, the error says " _Error: ENOENT: no such file or directory, open 'program.js'_ ".
you're opening "program.js" instead of "process.argv[2]", the files you are supposed to count the new lines is passed to you as the first argument of your program that's why you use "process.argv[2]".

**Comment by woodyb23** [comment]
@edwinharly  Thank you very much!
