### ISSUE TITLE
Out of memory error in MAKE IT MODULAR

### ISSUE THREAD

**Issue by IdleMuse** [nodeschool/discussions#1840]
I've been having an issue with MAKE IT MODULAR module, whereby I'm getting some sort of out-of-memory error. I can't see anything i'd consider dangerous in other languages (infinite loops etc.) which I'd expect to create this sort of error.

* node version: v0.12.15
* npm version:  2.15.1

### Error output
```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
```

### My Code
```js
 //program.js
var module_function = require("./module.js");
module_function(process.argv[2], process.argv[3], function callback(err, filtered_files){
  if(err) return err;
  for(fn of filtered_files) console.log(fn);
});

//----------------------------------------------------------------------------------------

//module.js
var fs = require('fs');
var path = require('path');

module.exports = filter_dir;

function filter_dir(path_to_search, extension, callback){
  var files = [];
  extension = "."+extension;
  fs.readdir(path_to_search, function callback(read_err, filename_array){
    if(read_err) return callback(read_err);
    for(fn of filename_array){
      if(fn.substring(fn.length-extension.length,fn.length) === extension) files.push(fn);
    }
    callback(null, files);
  });
}
```

If I comment out the line

```js
//if(fn.substring(fn.length-extension.length,fn.length) === extension) files.push(fn);
```

I get the following error output instead:

```
/vagrant/learnyounode/module.js:11
    for(fn of filename_array){
              ^
RangeError: Maximum call stack size exceeded
    at Array.values (native)
    at callback (/vagrant/learnyounode/module.js:11:15)
    at callback (/vagrant/learnyounode/module.js:14:5)
    at callback (/vagrant/learnyounode/module.js:14:5)
    at callback (/vagrant/learnyounode/module.js:14:5)
    at callback (/vagrant/learnyounode/module.js:14:5)
    at callback (/vagrant/learnyounode/module.js:14:5)
    at callback (/vagrant/learnyounode/module.js:14:5)
    at callback (/vagrant/learnyounode/module.js:14:5)
    at callback (/vagrant/learnyounode/module.js:14:5)
```

**Comment by IdleMuse** [comment]
Okay, problem fixed - I had (accidentally) named my anonymous function in modules.js, and naming it 'callback' confused everything.

Correct code:

```js
var fs = require('fs');
var path = require('path');

module.exports = filter_dir;

function filter_dir(path_to_search, extension, callback){
  var files = [];
  extension = "."+extension;
  fs.readdir(path_to_search, function(read_err, filename_array){
    if(read_err) return callback(read_err);
    for(fn of filename_array){
      if(fn.substring(fn.length-extension.length,fn.length) === extension) files.push(fn);
    }
    callback(null, files);
  });
}
```

**Comment by marinintim** [comment]
Yeah, you just recurse into readdir callback over and over again, each time doubling `files` array, until you've run out of memory.

Glad that you fixed this! I close this issue.
