### ISSUE TITLE
Cant download javascripting with npm

### ISSUE THREAD

**Issue by miroshnychenko** [nodeschool/discussions#1873]
Cant download javascripting with npm with enabled proxy and without it as well.

$ node -v
v4.5.0
### Error output

npm-debug.log file

```
 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--global',
1 verbose cli   'javascripting' ]
2 info using npm@2.15.9
3 info using node@v4.5.0
4 verbose install initial load of C:\Users\serhiim\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\serhiim\AppData\Roaming\npm\package.json
6 silly cache add args [ 'javascripting', null ]
7 verbose cache add spec javascripting
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'javascripting',
8 silly cache add   scope: null,
8 silly cache add   name: 'javascripting',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: 'latest',
8 silly cache add   type: 'tag' }
9 silly addNamed javascripting@latest
10 verbose addNamed "latest" is being treated as a dist-tag for javascripting
11 info addNameTag [ 'javascripting', 'latest' ]
12 silly mapToRegistry name javascripting
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry data Result {
15 silly mapToRegistry   raw: 'javascripting',
15 silly mapToRegistry   scope: null,
15 silly mapToRegistry   name: 'javascripting',
15 silly mapToRegistry   rawSpec: '',
15 silly mapToRegistry   spec: 'latest',
15 silly mapToRegistry   type: 'tag' }
16 silly mapToRegistry uri https://registry.npmjs.org/javascripting
17 verbose addNameTag registry:https://registry.npmjs.org/javascripting not in flight; fetching
18 verbose request uri https://registry.npmjs.org/javascripting
19 verbose request no auth needed
20 info attempt registry request try #1 at 9:37:07 AM
21 verbose request id 768c2f243cdf0172
22 http request GET https://registry.npmjs.org/javascripting
23 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=connect ETIMEDOUT 172.29.50.100:8080
24 info attempt registry request try #2 at 9:37:38 AM
25 http request GET https://registry.npmjs.org/javascripting
26 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=connect ETIMEDOUT 172.29.50.100:8080
27 info attempt registry request try #3 at 9:38:59 AM
28 http request GET https://registry.npmjs.org/javascripting
29 verbose stack Error: tunneling socket could not be established, cause=connect ETIMEDOUT 172.29.50.100:8080
29 verbose stack     at ClientRequest.onError (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:176:17)
29 verbose stack     at ClientRequest.g (events.js:260:16)
29 verbose stack     at emitOne (events.js:77:13)
29 verbose stack     at ClientRequest.emit (events.js:169:7)
29 verbose stack     at Socket.socketErrorListener (_http_client.js:269:9)
29 verbose stack     at emitOne (events.js:77:13)
29 verbose stack     at Socket.emit (events.js:169:7)
29 verbose stack     at emitErrorNT (net.js:1269:8)
29 verbose stack     at nextTickCallbackWith2Args (node.js:442:9)
29 verbose stack     at process._tickCallback (node.js:356:17)
30 verbose cwd D:\Projects\auto
31 error Windows_NT 6.3.9600
32 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--global" "javascripting"
33 error node v4.5.0
34 error npm  v2.15.9
35 error code ECONNRESET
36 error network tunneling socket could not be established, cause=connect ETIMEDOUT 172.29.50.100:8080
36 error network This is most likely not a problem with npm itself
36 error network and is related to network connectivity.
36 error network In most cases you are behind a proxy or have bad network settings.
36 error network
36 error network If you are behind a proxy, please make sure that the
36 error network 'proxy' config is set properly.  See: 'npm help config'
37 verbose exit [ 1, true ]

```

**Comment by stdrake95** [comment]
You need to install nodejs-legacy!
http://askubuntu.com/questions/702157/install-node-js-in-ubuntu-14-04
