### ISSUE TITLE
Error in learnyounode

### ISSUE THREAD

**Issue by vishugosain** [nodeschool/discussions#1896]
/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-adventure/node_modules/commandico/node_modules/joi/lib/index.js:5
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-adventure/node_modules/commandico/node_modules/explicit/lib/validate/index.js:3:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

This error while running learnyounode

**Comment by martinheidegger** [comment]
Thank you @vishugosain for reporting this. Would you mind to share the node version this happens on?

**Comment by CBedzz** [comment]
Sounds like you're running a very old version of Node (0.10 or 0.12?) where many of the ES6 features were not yet full supported.  Either upgrade your Node version, or I think you can run node with the --harmony flag to enable the features in the older version.
