### ISSUE TITLE
how-to-npm

### ISSUE THREAD

**Issue by gauravdesale** [nodeschool/discussions#1903]
### Notes
- If you have a question about the NodeSchool organization: Please open an issue in [nodeschool/organizers](https://github.com/nodeschool/organizers/issues/new)
- If you want to improve or contribute to workshoppers: Please open an issue in [workshopper/org](https://github.com/workshopper/org/issues/new)
- Did you see the guide for questions? https://github.com/nodeschool/discussions#when-you-have-a-problem

**Please delete this section after reading it**
### If you have a problem with an error message:
- node version: <run "node -v" in you terminal and replace this>
- npm version:  <run "npm -v" in you terminal and replace this>
- os: windows 7/windows 10/mac/linux
### Error output

```
 C:\Users\gauravdesale\AppData\Roaming\npm\node_modules\how-to-npm\node_modules\adventure\lib\menu.js:51
    process.stdin.setRawMode(true);
                  ^

TypeError: process.stdin.setRawMode is not a function
    at module.exports (C:\Users\gauravdesale\AppData\Roaming\npm\node_modules\how-to-npm\node_modules\adventure\lib\menu.js:51:19)
    at Shop.showMenu (C:\Users\gauravdesale\AppData\Roaming\npm\node_modules\how-to-npm\node_modules\adventure\index.js:258:16)
    at Shop.execute (C:\Users\gauravdesale\AppData\Roaming\npm\node_modules\how-to-npm\node_modules\adventure\index.js:122:14)
    at Shop.shop.execute (C:\Users\gauravdesale\AppData\Roaming\npm\node_modules\how-to-npm\index.js:37:45)
    at Object.<anonymous> (C:\Users\gauravdesale\AppData\Roaming\npm\node_modules\how-to-npm\index.js:86:8)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

```
### My Code

``` js
 when i run how-to-npm
```

**Comment by riyadhalnur** [comment]
Hi @gauravdesale. Thank you for reporting this. Could you specify the node version and OS you're using?
