### ISSUE TITLE
learnyounode verify not work for HTTP Collect 

### ISSUE THREAD

**Issue by Yeewind** [nodeschool/discussions#1916]
for the exercise after HTTP Collect, the verify function always return submission match, whatever code i input.

* node version: v4.5.0
* npm version:  3.10.9
* os: windows 7 Chrome 52.0.2743.116

### Error output
```
jxchen:~/workspace $ learnyounode verify newlines.js
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'http://localhost:42986'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.<anonymous> (/home/ubuntu/workspace/newlines.js:3:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)

Your submission results compared to the expected:

────────────────────────────────────────────────────────────────────────────────

1.  ACTUAL:    ""
1.  EXPECTED:  ""


────────────────────────────────────────────────────────────────────────────────

  ✓  Submission results match expected
```

### My Code
```js
 // copy your code here
```

**Comment by Yeewind** [comment]
problem solved. I did not install bl well. 

Only copy bl file is not enough, should also copy:
readable-stream
core-util-is
isarray
process-nextick-args
string_decoder
util-deprecate
inherits

**Comment by riyadhalnur** [comment]
@Yeewind Glad you got it sorted out. I'm closing the issue since it's working for you now. Please feel free to re-open if otherwise.
