### ISSUE TITLE
[Javascripting] Exercise #2/18 Variables SyntaxError: Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by Sunslinger00** [nodeschool/discussions#1954]
### Notes

I don't know what I'm doing incorrectly. Every other problem people seem to have the terminal says opps. Mine just says syntax error. Using text editor to edit the .js file.

### If you have a problem with an error message:

vagrant [javascripting]> node -v
v6.3.1
vagrant [javascripting]> npm -v
3.10.3

### Error output
```
vagrant [javascripting]> javascripting verify variables.js

# JAVASCRIPTING

## VARIABLES (Exercise 2 of 19)

{ Error: Command failed: node "/vagrant/javascripting/variables.js"
/vagrant/javascripting/variables.js:1
(function (exports, require, module, __filename, __dirname) { var example = ‘some string’;
                                                                            ^
SyntaxError: Unexpected token ILLEGAL
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node "/vagrant/javascripting/variables.js"' }
vagrant [javascripting]> node variables.js
/vagrant/javascripting/variables.js:1
(function (exports, require, module, __filename, __dirname) { var example = ‘some string’;
                                                                            ^
SyntaxError: Unexpected token ILLEGAL
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3

```

### My Code
```js

 var example = ‘some string’;
console.log(example);
```

**Comment by maxrimue** [comment]
The SyntaxError is about this line:
```javascript
var example = ‘some string’;
```

It might be hard to see, but you need different characters here. You use `‘` but actually need `'`, so the correct code would be:

```javascript
var example = 'some string';
console.log(example);
```

**Comment by Sunslinger00** [comment]
excellent, Thank you very much for your help.


# YOU CREATED A VARIABLE!

 Nice work.
