### ISSUE TITLE
Stuck on Make It Modular

### ISSUE THREAD

**Issue by Killmat** [nodeschool/discussions#1959]
I can't complete this one here is my code:

**make-it-modular.js**
```
var lol = require('module');

// lol.forEach(function (file) {
//   console.log(file);
// });

var dir = process.argv[2];
var ext = process.argv[3];

lol(dir, ext, function (err, list) {
  if (err) throw err;
  list.forEach(function (file) {
    console.log(file);
  });
});

```

**module.js**
```
var fs   = require('fs');
var path = require('path');


module.exports = function(dir, ext, callback) {
  fileList = [];

  fs.readdir(dir, function (err, files) {
    if (err) return callback(err);
    files.forEach(function (file) {
      if (path.extname(file) == '.' + ext) {
        fileList += file;
      }
    });
    return callback(null, fileList);
  });
};
```

The error i get is this 
```
module.js:38
  this.id = id;
          ^

TypeError: Cannot set property 'id' of undefined
    at Module (module.js:38:11)
    at Object.<anonymous> (C:\projekter\node.js\learnyounode\make-it-modular.js:10:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
```

**Comment by noffle** [comment]
`require` is used to gain access to the structures in `module.exports` in another JS file.

In `module.js` you've written `require('module')`. A module cannot `require` itself. Did you mean to require `make-it-modular.js` instead?

**Comment by Killmat** [comment]
@noffle I accidentally reversed the names up here, I edited it to be right. Do you have any idea what's wrong?

**Comment by aless80** [comment]
You wrote fileList += file;
Use fileList.push(file) instead because += is for adding numbers or concatenating strings
