### ISSUE TITLE
Exercise One - learn you react 

### ISSUE THREAD

**Issue by hellsinglord22** [nodeschool/discussions#1975]
### Versions

* node version: v6.9.1
* npm version:  3.10.8
* os: windows 10

### Problem Description 
I am following the first exercise **HELLO WORLD**  from [learnyoureact](https://github.com/kohei-takata/learnyoureact) workshop, 

I got the following error, 

```
+-- UNMET PEER DEPENDENCY react@15.4.2 
 `-- UNMET PEER DEPENDENCY react-dom@15.4.2
```

so installed every dependency on its own command after deleting the `node_modules` folder, 
and everything run fine but when trying to render `views/index.jsx` i get this error, 

### Error output
```
SyntaxError: E:/Code/node_school/react-workshop/views/index.jsx: Unexpected token (5:11)
  3 | export default class TodoBox extends React.Component{
  4 |   render() {
> 5 |     return <div className="todoBox">
    |            ^
  6 |         Hello, world!
  7 |       </div>
  8 |   }
    at Parser.pp$5.raise (E:\Code\node_school\react-workshop\node_modules\babylon\lib\index.js:4333:13)
    at Parser.pp.unexpected (E:\Code\node_school\react-workshop\node_modules\babylon\lib\index.js:1705:8)
    at Parser.pp$3.parseExprAtom (E:\Code\node_school\react-workshop\node_modules\babylon\lib\index.js:3670:12)
    at Parser.pp$3.parseExprSubscripts (E:\Code\node_school\react-workshop\node_modules\babylon\lib\index.js:3414:19)
    at Parser.pp$3.parseMaybeUnary (E:\Code\node_school\react-workshop\node_modules\babylon\lib\index.js:3394:19)
    at Parser.pp$3.parseExprOps (E:\Code\node_school\react-workshop\node_modules\babylon\lib\index.js:3324:19)
    at Parser.pp$3.parseMaybeConditional (E:\Code\node_school\react-workshop\node_modules\babylon\lib\index.js:3301:19)
    at Parser.pp$3.parseMaybeAssign (E:\Code\node_school\react-workshop\node_modules\babylon\lib\index.js:3264:19)
    at Parser.pp$3.parseExpression (E:\Code\node_school\react-workshop\node_modules\babylon\lib\index.js:3226:19)
    at Parser.pp$1.parseReturnStatement (E:\Code\node_school\react-workshop\node_modules\babylon\lib\index.js:2024:26)
```

## program.js
```js
 var express = require('express');
var app = express();

app.set('port', (process.argv[2] || 3000));
app.set('view engine', 'jsx');
app.set('views', __dirname + '/views');
app.engine('jsx', require('express-react-views').createEngine({ transformViews: false }));

require('babel-register')({
    ignore: false
});

app.use('/', function(req, res) {
  res.render('index', '');
});

app.listen(app.get('port'), function() {});
```

## index.jsx
```js
import React from 'react';

export default class TodoBox extends React.Component{
  render() {
    return <div className="todoBox">
        Hello, world!
      </div>
  }
}
```

## package.json
```json
{
  "name": "react-workshop",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "babel": "^6.5.2",
    "body-parser": "^1.16.0",
    "express": "^4.14.0",
    "express-react-views": "^0.10.2",
    "react": "^15.4.2",
    "react-dom": "^15.4.2"
  }
}
```

**Comment by Goyapa** [comment]
Try to wrap returned div with braces ()
`javascript
render() {
    return (<div className="todoBox">
        Hello, world!
      </div>
)
  }
`
