### ISSUE TITLE
Learnyounode Ex 6 of 13 : Make it modular `Could not verify: TypeError: ...`

### ISSUE THREAD

**Issue by cyc115** [nodeschool/discussions#1979]
> node -v : v7.4.0
> npm -v : 4.0.5
> OS : ubuntu 14.04

I have the following files in `./` : `index.js` and `E6.js`

# index.js 
```javascript
'use strict'
var filterByExt = require('./E6')

var dir = process.argv[2] || './'
var ext = process.argv[3] || 'js'
var cb = process.argv[4] || ` (err, inf) =>{console.log('default callback\\n' + inf)}`

filterByExt(dir, ext, eval(cb))
```
# E6.js 
```javascript
var filterByExt = function (dir, ext, callback) {
  var fs = require('fs')

  fs.readdir(dir, (err, files) => {
    if (err) {
      callback(err, null)
      return
    }

    var result = files.filter(v => {
      let vs = v.split('.')
      if (vs[vs.length - 1] == ext && vs.length >= 2) {
        return v
      }
    })

    callback(null, result)
    return 
  })
}

module.exports = filterByExt
```

I am getting the following error when executing `learnyounode verify`, however `node index.js` runs just fine. Any Ideas ? :) I just can't understand the stacktrace ( I am coming from Java and this seems to be quite often the case in JS). Are there better ways to debug ? 

Thanks in advance!

```
Could not verify: TypeError: Cannot read property 'toString' of undefined
    at Exercise.setup (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/filecheck.js:8:21)
    at next (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:145:15)
    at Exercise.setup (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:151:5)
    at Exercise.runVerify (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:158:8)
    at Exercise.verify (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:173:13)
    at WA.executeExercise (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-adventure/index.js:425:16)
    at WA.process (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-adventure/index.js:317:17)
    at WA.verify (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-adventure/index.js:258:15)
    at Object.exports.handler.exports.handler (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-adventure/lib/commands/verify.js:12:21)
    at method.valid.$ (/usr/local/lib/node_modules/learnyounode/node_modules/commandico/commandico.js:143:15)
```

**Comment by cyc115** [comment]
Turns out I forgot to pass in `index.js` as `learnyounode verify`.
