### ISSUE TITLE
Error verifying "Make it Modular" @ .../learnyounode/node_modules/workshopper-exercise/exercise.js

### ISSUE THREAD

**Issue by secretexclusiveclub** [nodeschool/discussions#1981]
### Notes

* node version: v7.4.0
* npm version:  v4.0.5
* os: macOS Sierra

### Error output
when running `learnyounode verify program.js`

```
 ✓ 

 Submission results match expected

 ✓ 

 Additional module file exports a single function

 ✓ 

 Additional module file exports a function that takes 3 arguments

 ✓ 

 Additional module file handles errors properly

 ✓ 

 Additional module file handles callback argument

/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:188
    processors[i].call(self, mode, function (err, pass) {
                 ^

TypeError: Cannot read property 'call' of undefined
    at next (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:188:18)
    at /usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:195:7
    at callback (/usr/local/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:26:15)
    at modFileError (/usr/local/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:31:5)
    at /usr/local/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:130:18
    at cb (/Users/josh/Documents/coding/njslearn/ex6/mymodule.js:13:11)
    at FSReqWrap.oncomplete (fs.js:112:15)
```

### My Code
program.js

```js
var mymodule = require("./mymodule.js");

var cb = function (err, data) {
  if (err) {
    console.log(err);
  } else {
    console.log(data);
  }
}

mymodule(process.argv[2], process.argv[3], cb)
```

mymodule.js

```js
var fs = require('fs');
var path = require('path');
module.exports = function (dir, given_ext, cbreturn) {

  var cb = function (err, list) {

    if (err) {
      cbreturn(err);
    } else {
      for (var i = 0; i < list.length; i++) {
        ext = path.extname(list[i]).substring(1);
        if (ext == given_ext) {
          cbreturn(err, list[i]);
        }
      }
    }
  };
  fs.readdir(dir, cb);

};
```

**Comment by oyeuva** [comment]
check out: `https://github.com/nodeschool/discussions/issues/1606`
