### ISSUE TITLE
My first ASYNC I/O 

### ISSUE THREAD

**Issue by tornikegomareli** [nodeschool/discussions#1983]
### Notes

I'm trying to solve nodejs solutions, **My first ASYNC I/O** 

# HINTS

  The solution to this problem is almost the same as the previous problem
  except you must now do it the Node.js way: asynchronous.

  Instead of fs.readFileSync() you will want to use fs.readFile() and
  instead of using the return value of this method you need to collect the
  value from a callback function that you pass in as the second argument. To
  learn more about callbacks, check out:
  [https://github.com/maxogden/art-of-node#callbacks](https://github.com/max
  ogden/art-of-node#callbacks).

  Remember that idiomatic Node.js callbacks normally have the signature:

     function callback (err, data) { /* ... */ }

  so you can check if an error occurred by checking whether the first
  argument is truthy. If there is no error, you should have your Buffer
  object as the second argument. As with readFileSync(), you can supply
  'utf8' as the second argument and put the callback as the third argument
  and you will get a String instead of a Buffer.

**i tested and i think my solution is OK.**

first of all im typing

**$ node test,js ./test.js**

**output is 6**

But when I'm typing
**learnyounode**  verify i have error message here
### Error output
tornikegomareli:~/workspace $ learnyounode verify

Could not verify: TypeError: Cannot read property 'toString' of undefined
    at Exercise.setup (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/learnyounode/node_modules/workshopper-exercise/filecheck.js:8:21)
    at next (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:145:15)
    at Exercise.setup (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:151:5)
    at Exercise.runVerify (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:158:8)
    at Exercise.verify (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:173:13)
    at WA.executeExercise (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/learnyounode/node_modules/workshopper-adventure/index.js:425:16)
    at WA.process (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/learnyounode/node_modules/workshopper-adventure/index.js:317:17)
    at WA.verify (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/learnyounode/node_modules/workshopper-adventure/index.js:258:15)
    at Object.exports.handler.exports.handler [as handler] (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/learnyounode/node_modules/workshopper-adventure/lib/commands/verify.js:12:21)
    at Object.explicit.execute.$ (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/learnyounode/node_modules/commandico/commandico.js:143:15)
tornikegomareli:~/workspace $ 
### My Code
var fs = require('fs');

fs.readFile(process.argv[2],'utf8',function (err, data) {
  var lines = data.split('\n').length - 1;
  console.log(lines);
});

**Comment by noffle** [comment]
What happens if you try `learnyounode verify test.js`?

**Comment by mkermouss** [comment]
the method fs.readFile is asynchronous method, to pass the exercice you need to use a synchronous method.

**Comment by mkermouss** [comment]
again you can try with this solution : 
`
var fs = require('fs');
var path = process.argv[2];
var content = fs.readFileSync(path,'utf8');
console.log(content.split('\n').length - 1);
`
