### ISSUE TITLE
SENECA IN PRACTICE - Plugin - Exercise 3 of 12

### ISSUE THREAD

**Issue by sdurighello** [nodeschool/discussions#1997]
* node version: v7.2.0
* npm version:  3.10.9
* os: mac

### Error output
```
Calling plugin with left: 90, right: 54
{"kind":"notice","notice":"hello seneca gmftpp1zwx6g/1486153915040/12088/3.2.2/-","level":"info","when":1486153915064}
{"kind":"notice","notice":"hello seneca nmjdtqidbktf/1486153915306/12088/3.2.2/-","level":"info","when":1486153915361}
[]
{"notice":"seneca: closed","code":"closed","err":{"eraro":true,"orig":null,"code":"closed","seneca":true,"package":"seneca","msg":"seneca: closed","details":{"args":"{ role: 'math', cmd: 'sum', left: 90, right: 54 }","plugin":{}},"callpoint":"at handle_inward_break (/Users/sdurighello/.nvm/versions/node/v7.2.0/lib/node_modules/seneca-in-practice/node_modules/seneca/seneca.js:1155:23)"},"msg":{"role":"math","cmd":"sum","left":90,"right":54,"meta$":{}},"meta":{},"listen":false,"transport":{},"kind":"act","case":"ERR","duration":1,"level":"error","when":1486153915492}
{ Error: seneca: closed
    at Object.errormaker [as error] (/Users/sdurighello/.nvm/versions/node/v7.2.0/lib/node_modules/seneca-in-practice/node_modules/eraro/eraro.js:94:15)
    at handle_inward_break (/Users/sdurighello/.nvm/versions/node/v7.2.0/lib/node_modules/seneca-in-practice/node_modules/seneca/seneca.js:1155:23)
    at execute_action (/Users/sdurighello/.nvm/versions/node/v7.2.0/lib/node_modules/seneca-in-practice/node_modules/seneca/seneca.js:1050:11)
    at Object.act_fn [as fn] (/Users/sdurighello/.nvm/versions/node/v7.2.0/lib/node_modules/seneca-in-practice/node_modules/seneca/seneca.js:1013:11)
    at Immediate.processor (/Users/sdurighello/.nvm/versions/node/v7.2.0/lib/node_modules/seneca-in-practice/node_modules/gate-executor/gate-executor.js:136:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
  eraro: true,
  orig: null,
  code: 'closed',
  seneca: true,
  package: 'seneca',
  msg: 'seneca: closed',
  details: 
   { args: '{ role: \'math\', cmd: \'sum\', left: 90, right: 54 }',
     plugin: {} },
  callpoint: 'at handle_inward_break (/Users/sdurighello/.nvm/versions/node/v7.2.0/lib/node_modules/seneca-in-practice/node_modules/seneca/seneca.js:1155:23)' }


Seneca Fatal Error
==================

Message: seneca: use-plugin: No name property found for plugin defined by Object {}.

Code: plugin_no_name

Details: { 'orig$': 
   { Error: use-plugin: No name property found for plugin defined by Object {}.
       at errormaker (/Users/sdurighello/.nvm/versions/node/v7.2.0/lib/node_modules/seneca-in-practice/node_modules/eraro/eraro.js:94:15)
       at build_plugindesc (/Users/sdurighello/.nvm/versions/node/v7.2.0/lib/node_modules/seneca-in-practice/node_modules/use-plugin/use.js:148:46)
       at Object.use (/Users/sdurighello/.nvm/versions/node/v7.2.0/lib/node_modules/seneca-in-practice/node_modules/use-plugin/use.js:78:22)
       at Seneca.api_use [as use] (/Users/sdurighello/.nvm/versions/node/v7.2.0/lib/node_modules/seneca-in-practice/node_modules/seneca/seneca.js:954:29)
       at Object.<anonymous> (/Users/sdurighello/.nvm/versions/node/v7.2.0/lib/node_modules/seneca-in-practice/problems/plugin/seneca-plugin-executor.js:18:8)
       at Module._compile (module.js:571:32)
       at Object.Module._extensions..js (module.js:580:10)
 // copy your error output here
```

### My Code
```js
 // operations.js
module.exports = function plugin(options) {

    this.add({role: 'math', cmd: 'sum'}, (msg, respond) => {
        const sum = msg.left + msg.right;
        respond(null, {answer: sum});
    });

    return 'operations'
};

// client.js
const seneca = require('seneca')();
const operations = require('./operations');

const left = parseInt(process.argv[2]);
const right = parseInt(process.argv[3]);

seneca.use('./operations', {});

seneca.ready(function (err) {
    if(err) return console.error(err);
    seneca.act({role: 'math', cmd: 'sum', left: left, right: right}, console.log)
});
```

**Comment by sdurighello** [comment]
Although I get an error when I run `seneca-in-practice run client.js`
the code seems to work when run with `node client.js 12 1` :
```
{"kind":"notice","notice":"hello seneca 818x3e4yhpvj/1486368448251/12544/3.2.2/-","level":"info","when":1486368448271}
(node:12544) DeprecationWarning: 'root' is deprecated, use 'global'
null { answer: 13 }

```

**Comment by brandonros** [comment]
@sdurighello > Although I get an error when I run seneca-in-practice run client.js
the code seems to work when run with node client.js 12 1 :

Can you share what you changed?

**Comment by laur3d** [comment]
Having exaclty the same problem
works with node index.js 1 3
`
// index.js
const seneca = require('seneca')();

const left = Number(process.argv[2]);
const right = Number(process.argv[3]);

seneca.use('./operations', {});

seneca.ready(function (err) {
    if(err) return console.error(err);
    
    console.log(seneca.hasplugin('operations'));
    
    seneca.act({role: 'math', cmd: 'sum', left: left, right: right}, (err, response) => {
        if(err) console.error(err);
        console.log(response); 
    });
});

//operations.js

'use strict'

module.exports = function (options) {
    
    this.add({role: 'math', cmd:'sum'}, function(msg, next){
       next(null, {answer: (msg.left + msg.right)});
    });
    
    return 'operations';
}

// console
(node:7440) DeprecationWarning: 'root' is deprecated, use 'global'
{"kind":"notice","notice":"hello seneca 2w00hm4m3ijo/1487694626984/7440/3.3.0/-","level":"info","when":1487694627216}
true
{ answer: 4 }

`

but getting the same crash if i try with the seneca- command ...

**Comment by CExMMartinez** [comment]
These are very old, but the issue you were experiencing above is the task only wants you to define a plugin module. You don't need to define the client in this exercise.
