### ISSUE TITLE
FILTERED LS - Err "Cannot read property 'readdir' of undefined"

### ISSUE THREAD

**Issue by bgee4** [nodeschool/discussions#2016]
Attempting to complete exercise 5 (FILTERED LS), readdir is throwing an undefined error.  Any help is appreciated. Thanks

* node version: v4.6.1
* npm version:  2.15.9
* os: chromeOS (using Cloud9 IDE)

### Error output
```
fs.readdir(process.argv[2], function(err, files){
  ^

TypeError: Cannot read property 'readdir' of undefined
    at Object.<anonymous> (/home/ubuntu/workspace/learnyounode/filterls.js:5:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
```

### My Code
```js
const fs = require.fs
const path = require.path
var exttype = "." + process.argv[3]

fs.readdir(process.argv[2], function(err, files){
    if (err) {
        return console.log(err)
    }
    
    for (var i = 0; i<files.length; i++){
        if(path.extname(files.argv[i]) == exttype){
            console.log(files.argv[i])
        }
    }

})
```

**Comment by ryanlondon** [comment]
I'm just going through the exercises myself but I think the problem is with the syntax in your require statements. "Require" is a method that takes a string so it should be:
`const fs = require('fs');
const path = require('path');`

**Comment by bgee4** [comment]
ah that's it, don't know how I missed it! Thanks
