### ISSUE TITLE
learnyounode - windows7 - what folder do I save exercises to?

### ISSUE THREAD

**Issue by Brian-Seattle** [nodeschool/discussions#2022]
node -v   v6.10.0
npm -v  3.10.0
OS - Windows 7

###Error output
C:\Users\ligia>learnyounode run brianhelloworld.js
Could not run: Error: No such file: C:\Users\ligia\brianhelloworld.js
    at Exercise.<anonymous> (C:\Users\ligia\AppData\Roaming\npm\node_modules\lea
rnyounode\node_modules\workshopper-exercise\filecheck.js:10:23)
    at FSReqWrap.oncomplete (fs.js:123:15)
Could not run: Error: No such file: C:\Users\ligia\brianhelloworld.js
    at Exercise.<anonymous> (C:\Users\ligia\AppData\Roaming\npm\node_modules\lea
rnyounode\node_modules\workshopper-exercise\filecheck.js:10:23)
    at FSReqWrap.oncomplete (fs.js:123:15)

**Comment by abyabrkal** [comment]
Dear @Brian-Seattle,

in cmd prompt, you need to traverse to exercise file location to run the particular js.

Once cmd opens, it defaults to user folder **C:\Users\ligia** and give you a prompt **'>'**

Then, you can go to your excercise folder by using **cd** (change directory) command.

`cd AppData\Roaming\npm\node_modules\learnyounode\node_modules\workshopper-exercise`

Most probably, this is where you saved all your workshopper files by default (if you didn't change your directory manually while installation).
