### ISSUE TITLE
Baby Steps - syntax for sum?

### ISSUE THREAD

**Issue by kevkhayat** [nodeschool/discussions#2028]
### Error output
```
c:\Users\kevkh\learnyounodelesson2.js:1
(function (exports, require, module, __filename, __dirname) { process.argv();
                                                                      ^

TypeError: process.argv is not a function
    at Object.<anonymous> (c:\Users\kevkh\learnyounodelesson2.js:1:71)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED
────────────────────────────────────────────────────────────────────────────────

   ""                                  !=    "244"
                                       !=    ""

────────────────────────────────────────────────────────────────────────────────

 ✗

 Submission results did not match expected!

 # FAIL Your solution to BABY STEPS didn't pass. Try again!
```

### My Code

```js
process.argv();
var arraylength = process.argv.length;
var sum = 0;
var i = 3;
for (i < arraylength; i++; {
        sum: +number(process.argv[i])
    }) {
    console.log(sum);
}
```

I've tried a few different ways to iterate the sum for each item of the array but can't get it to work.  There could be other problems... thanks everyone (anyone!).

**Comment by kevkhayat** [comment]
The indents on the code haven't come through...

**Comment by hodorswit** [comment]
On the first line you are calling `process.argv()` as though it were a function, but it is an Array. 

Your code has a few other syntax related issues. Have you done any Javascript programming before? If not, learnyounode might not be the best starting point for a beginner. 

I can 100% recommend Eloquent Javascript as a great jumping-off point: http://eloquentjavascript.net/

**Comment by milesibastos** [comment]
At the first line: process.argv is not a function!
Check this sample:
https://asciinema.org/a/107298
