### ISSUE TITLE
TypeError: inst.render is not a function in excerise3 of learnyoureact

### ISSUE THREAD

**Issue by zyMacro** [nodeschool/discussions#2039]
* node version: v7.5.0
* npm version:  4.1.2
* os: mac

### Error output
```
TypeError: inst.render is not a function
    at /Users/zyhkevin21/Documents/nodeschool/learnyoureact/node_modules/react-dom/lib/ReactCompositeComponent.js:796:21
    at measureLifeCyclePerf (/Users/zyhkevin21/Documents/nodeschool/learnyoureact/node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/Users/zyhkevin21/Documents/nodeschool/learnyoureact/node_modules/react-dom/lib/ReactCompositeComponent.js:795:25)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/Users/zyhkevin21/Documents/nodeschool/learnyoureact/node_modules/react-dom/lib/ReactCompositeComponent.js:822:32)
    at ReactCompositeComponentWrapper.performInitialMount (/Users/zyhkevin21/Documents/nodeschool/learnyoureact/node_modules/react-dom/lib/ReactCompositeComponent.js:362:30)
    at ReactCompositeComponentWrapper.mountComponent (/Users/zyhkevin21/Documents/nodeschool/learnyoureact/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/Users/zyhkevin21/Documents/nodeschool/learnyoureact/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at /Users/zyhkevin21/Documents/nodeschool/learnyoureact/node_modules/react-dom/lib/ReactServerRendering.js:45:36
    at ReactServerRenderingTransaction.perform (/Users/zyhkevin21/Documents/nodeschool/learnyoureact/node_modules/react-dom/lib/Transaction.js:140:20)
    at renderToStringImpl (/Users/zyhkevin21/Documents/nodeschool/learnyoureact/node_modules/react-dom/lib/ReactServerRendering.js:43:24)
```

### My Code
```
just copy the initial code
```
Furthermore,When I run the code passed in the last exercise, same error happens

**Comment by vampcoder** [comment]
Just copy the code of todobox and todoform from the last exercise in the omitted section.
