### ISSUE TITLE
Exercise 6: Unsure how to have files communicate, confusion with async

### ISSUE THREAD

**Issue by TheIncorrigible1** [nodeschool/discussions#2044]
### Error output
```
/home/ubuntu/workspace/module.js:10
module.exports = function (list, ext, callback(err, data) {
                                              ^

SyntaxError: Unexpected token (
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/workspace/filteredls.js:1:78)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

### My Code
```js
var mymodule = require('./module');
var list = mymodule(process.argv[2], process.argv[3], callback());
console.log(list);
```
```js
var fs = require('fs');
const path = require('path');

module.exports = function (list, ext, callback(err, data) {
  if (err) return err;
  callback(null, data);
}) {

  var ls = fs.readdir(list, function callback(err, dir) {
    if (err) return err;

    ext = "." + ext;
    var ret = [];
    for (var i = 0; i < list.length; i++)
    {
      if (path.extname(list[i]) == ext) ret.push(list[i]);
    }

  return ret;
  });

return ls;
}
```

**Comment by TheIncorrigible1** [comment]
I figured it out.  Here's my solution that I came up with:

```js
var fs = require('fs');
var path = require('path');

module.exports = function (dir, ext, callback) {
   fs.readdir(dir, function (err, data) {
    if (err) return callback(err);

    var list = [];

    for (var i = 0; i < data.length; i++)
    {
      if (path.extname(data[i]) == "." + ext) { list.push(data[i]); }
    }

    callback(null, list);
  });
}
```

```js
var mymodule = require('./module');
var dir = process.argv[2],
    ext = process.argv[3];
mymodule(dir, ext, function(err, list) {
  if (err) console.error(err);

  list.forEach(function(element) { console.log(element); });
});
```
