### ISSUE TITLE
Can't Publish Package (Failed PUT 404)

### ISSUE THREAD

**Issue by jackuhlantern** [nodeschool/discussions#2049]
I'm getting an error message while trying the Publish challenge; I'm not as familiar with all the tech talk I've seen in some other threads and they all seem to be for older versions. Any help would be appreciated. Also, please let me know if I'm leaving out any information.

node v 6.10.1
npm v 4.4.4 
os: Windows 10

after the command >npm publish
### Error output
```
npm ERR! publish Failed PUT 404
npm ERR! code E404
npm ERR! 404 missing : @jackuhlantern/one
npm ERR! 404
npm ERR! 404  '@jackuhlantern/one' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\--\AppData\Roaming\npm-cache\_logs\2017-03-27T04_26_32_574Z-debug.log
```
Full debug log:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\--\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'publish' ]
2 info using npm@4.4.4
3 info using node@v6.10.1
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec Result {
7 silly cache add   raw: '.',
7 silly cache add   scope: null,
7 silly cache add   escapedName: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: 'C:\\Users\\--\\npm_stuff',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory C:\Users\--\AppData\Roaming\npm-cache\@jackuhlantern\one\1.0.2\package.tgz not in flight; packing
9 verbose correctMkdir C:\Users\--\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
10 info lifecycle @jackuhlantern/one@1.0.2~prepublish: @jackuhlantern/one@1.0.2
11 silly lifecycle @jackuhlantern/one@1.0.2~prepublish: no script for prepublish, continuing
12 info lifecycle @jackuhlantern/one@1.0.2~prepare: @jackuhlantern/one@1.0.2
13 silly lifecycle @jackuhlantern/one@1.0.2~prepare: no script for prepare, continuing
14 verbose tar pack [ 'C:\\Users\\--\\AppData\\Roaming\\npm-cache\\@jackuhlantern\\one\\1.0.2\\package.tgz',
14 verbose tar pack   'C:\\Users\\--\\npm_stuff' ]
15 verbose tarball C:\Users\--\AppData\Roaming\npm-cache\@jackuhlantern\one\1.0.2\package.tgz
16 verbose folder C:\Users\--\npm_stuff
17 verbose addLocalTarball adding from inside cache C:\Users\--\AppData\Roaming\npm-cache\@jackuhlantern\one\1.0.2\package.tgz
18 verbose correctMkdir C:\Users\--\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
19 silly cache afterAdd @jackuhlantern/one@1.0.2
20 verbose afterAdd C:\Users\--\AppData\Roaming\npm-cache\@jackuhlantern\one\1.0.2\package\package.json not in flight; writing
21 verbose correctMkdir C:\Users\--\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
22 verbose afterAdd C:\Users\--\AppData\Roaming\npm-cache\@jackuhlantern\one\1.0.2\package\package.json written
23 silly publish { name: '@jackuhlantern/one',
23 silly publish   version: '1.0.2',
23 silly publish   description: 'first go',
23 silly publish   main: 'index.js',
23 silly publish   scripts: { test: 'node test.js' },
23 silly publish   repository: { type: 'git', url: 'npmjs.com' },
23 silly publish   keywords: [ 'one', 'first', 'npm' ],
23 silly publish   author: { name: 'V' },
23 silly publish   license: 'ISC',
23 silly publish   dependencies: { '@linclark/pkg': '^1.0.2' },
23 silly publish   devDependencies: {},
23 silly publish   readme: 'a few words\r\n',
23 silly publish   readmeFilename: 'README.md',
23 silly publish   _id: '@jackuhlantern/one@1.0.2',
23 silly publish   _shasum: 'a382a56ba9b9d0cf84a0c0c7c3371c0310e65552',
23 silly publish   _from: '.' }
24 info lifecycle @jackuhlantern/one@1.0.2~prepublishOnly: @jackuhlantern/one@1.0.2
25 silly lifecycle @jackuhlantern/one@1.0.2~prepublishOnly: no script for prepublishOnly, continuing
26 verbose getPublishConfig undefined
27 silly mapToRegistry name @jackuhlantern/one
28 silly mapToRegistry scope (from package name) @jackuhlantern
29 verbose mapToRegistry no registry URL found in name for scope @jackuhlantern
30 silly mapToRegistry using default registry
31 silly mapToRegistry registry http://localhost:15443/
32 silly mapToRegistry data Result {
32 silly mapToRegistry   raw: '@jackuhlantern/one',
32 silly mapToRegistry   scope: '@jackuhlantern',
32 silly mapToRegistry   escapedName: '@jackuhlantern%2fone',
32 silly mapToRegistry   name: '@jackuhlantern/one',
32 silly mapToRegistry   rawSpec: '',
32 silly mapToRegistry   spec: 'latest',
32 silly mapToRegistry   type: 'tag' }
33 silly mapToRegistry uri http://localhost:15443/@jackuhlantern%2fone
34 verbose publish registryBase http://localhost:15443/
35 silly publish uploading C:\Users\--\AppData\Roaming\npm-cache\@jackuhlantern\one\1.0.2\package.tgz
36 verbose request uri http://localhost:15443/@jackuhlantern%2fone
37 verbose request sending authorization for write operation
38 info attempt registry request try #1 at 1:26:32 PM
39 verbose request id 7550712cbaa22e75
40 http request PUT http://localhost:15443/@jackuhlantern%2fone
41 http 404 http://localhost:15443/@jackuhlantern%2fone
42 verbose headers { 'content-type': 'application/json',
42 verbose headers   date: 'Mon, 27 Mar 2017 04:26:32 GMT',
42 verbose headers   connection: 'keep-alive',
42 verbose headers   'content-length': '19' }
43 verbose request invalidating C:\Users\--\AppData\Roaming\npm-cache\localhost_15443\_40jackuhlantern_252fone on PUT
44 error publish Failed PUT 404
45 verbose stack Error: missing : @jackuhlantern/one
45 verbose stack     at makeError (C:\Users\--\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:304:12)
45 verbose stack     at CachingRegistryClient.<anonymous> (C:\Users\--\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:292:14)
45 verbose stack     at Request._callback (C:\Users\--\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:212:14)
45 verbose stack     at Request.self.callback (C:\Users\--\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:188:22)
45 verbose stack     at emitTwo (events.js:106:13)
45 verbose stack     at Request.emit (events.js:191:7)
45 verbose stack     at Request.<anonymous> (C:\Users\--\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:1171:10)
45 verbose stack     at emitOne (events.js:96:13)
45 verbose stack     at Request.emit (events.js:188:7)
45 verbose stack     at IncomingMessage.<anonymous> (C:\Users\V\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:1091:12)
46 verbose statusCode 404
47 verbose pkgid @jackuhlantern/one
48 verbose cwd C:\Users\--\npm_stuff
49 verbose Windows_NT 10.0.14393
50 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\--\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "publish"
51 verbose node v6.10.1
52 verbose npm  v4.4.4
53 error code E404
54 error 404 missing : @jackuhlantern/one
55 error 404
56 error 404 '@jackuhlantern/one' is not in the npm registry.
57 error 404 You should bug the author to publish it (or use the name yourself!)
58 error 404 Note that you can also install from a
59 error 404 tarball, folder, http url, or git url.
60 verbose exit [ 1, true ]
```

### My Code
```js
{
  "name": "@jackuhlantern/one",
  "version": "1.0.2",
  "description": "first go",
  "main": "index.js",
  "scripts": {
    "test": "node test.js"
  },
  "repository": {
    "type": "git",
    "url": "npmjs.com"
  },
  "keywords": [
    "one",
    "first",
    "npm"
  ],
  "author": "V",
  "license": "ISC",
  "dependencies": {
    "@linclark/pkg": "^1.0.2"
  },
  "devDependencies": {}
}
```

**Comment by jackuhlantern** [comment]
Is there a way to bump this or have I done something wrong? Because it's been more than a month now and I haven't heard anything.

**Comment by shokry-suleiman** [comment]
I'm also have this error

**Comment by chadberchek** [comment]
The answer in #1561 worked for me. I am using more recent versions too:

node: v8.0.0
npm: 5.0.3

The answer is saying you need to create an empty folder inside the folders used by the fake npm repository server to work around a bug in it. For example my Windows home directory is `C:\Users\vobar`, my fake npm user name is `chad`, and my package name is `myhowtonpm`. After you try to run `npm publish` and it fails, you will find a directory structure like this:

`C:\Users\vobar\.config\how-to-npm\registry\@chad\myhowtonpm\-`

<img width="201" alt="before" src="https://user-images.githubusercontent.com/12478871/27254474-58ccc490-534e-11e7-924f-b93057bec228.png">

You need to create an empty folder inside this folder having as its name an @ sign followed by your fake npm user name:

<img width="190" alt="after" src="https://user-images.githubusercontent.com/12478871/27254481-adf6d708-534e-11e7-9bd0-6e07ec3e4abc.png">
