### ISSUE TITLE
toString error in Modular Assignment

### ISSUE THREAD

**Issue by matthew-t-smith** [nodeschool/discussions#2088]
When I run `learnyounode run originalProgram.js` I get the output I expect. However, when I go to run `learnyounode verify` I get the error below about toString being passed an undefined. Not sure if this has to do with the `fs.readdir` encoding attribute or what? Any help is greatly appreciated.

### If you have a problem with an error message:
* node version: v4.6.1
* npm version:  4.5.0
* os: macOS

### Error output
```
Could not verify: TypeError: Cannot read property 'toString' of undefined
    at Exercise.setup (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/learnyounode/node_modules/workshopper-exercise/filecheck.js:8:21)
    at next (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:145:15)
    at Exercise.setup (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:151:5)
    at Exercise.runVerify (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:158:8)
    at Exercise.verify (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:173:13)
    at WA.executeExercise (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/learnyounode/node_modules/workshopper-adventure/index.js:425:16)
    at WA.process (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/learnyounode/node_modules/workshopper-adventure/index.js:317:17)
    at WA.verify (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/learnyounode/node_modules/workshopper-adventure/index.js:258:15)
    at Object.exports.handler.exports.handler [as handler] (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/learnyounode/node_modules/workshopper-adventure/lib/commands/verify.js:12:21)
    at Object.explicit.execute.$ (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/learnyounode/node_modules/commandico/commandico.js:143:15)
```

### My Code
**originalProgram.js**
```js
var myMod = require('./moduleProgram.js');

var cb = function (err, data3) {
   if (err) {
      console.log(err);
   }
   for (var k = 0; k < data3.length; k++)
      console.log(data3[k]);
};

var directory = process.argv[2];
var filter = process.argv[3];
myMod(directory, filter, cb);
```

**moduleProgram.js**
```js
var path = require('path');
var fs = require('fs');

module.exports = function (directory, filter, callback) {
    fs.readdir(directory.toString(), function (err, data) {
        if (err) {
            return callback(err);
        }
        var ext = "." + filter;
        var data2 = [];
        for (var i = 0; i < data.length; i++) {
            if (path.extname(data[i]) == ext) {
                data2.push(data[i]);
            }
        }
        return callback(null, data2);
    });
  };
```

**Comment by jordanSu** [comment]
Hi,
Did you only enter `learnyounode verify` ?
If you did, you should enter `learnyounode verify originalProgram.js` to verify it.
Hope it helps ^_^

**Comment by matthew-t-smith** [comment]
Yes, sorry, I did use ```learnyounode verify originalProgram.js``` originally.
