### ISSUE TITLE
err msg

### ISSUE THREAD

**Issue by himanshusaini111** [nodeschool/discussions#2099]
v7.10.0
4.2.0
windows 10

### Error output

```
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\Malware\Desktop\file:\C:\Users\Malware\AppData\Roami
ng\npm\node_modules\learnyounode\node_apidoc\fs.html#fs_fs_readfilesync_filename_options'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.<anonymous> (C:\Users\Malware\Desktop\program.js:3:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
```

### My Code

```js
var fs = require('fs');

var buf = fs.readFileSync(process.argv[2]);

var str = buf.toString();

var arr = str.split('\n');

console.log(arr.length-1);
```

**Comment by himanshusaini111** [comment]
actually the second line is giving the error

**Comment by davecocoa** [comment]
How are you running this? Did you run `learnyounode verify program.js` or `learnyounode run program.js`?
