### ISSUE TITLE
Cannot find module 'process-nextick-args'

### ISSUE THREAD

**Issue by JustinBeuck** [nodeschool/discussions#2100]
### Notes

- If you have a question about the NodeSchool organization: Please open an issue in [nodeschool/organizers](https://github.com/nodeschool/organizers/issues/new)
- If you want to improve or contribute to workshoppers: Please open an issue in [workshopper/org](https://github.com/workshopper/org/issues/new)
- Did you see the guide for questions? https://github.com/nodeschool/discussions#when-you-have-a-problem

**Please delete this section after reading it**

### If you have a problem with an error message:

* node version: v7.10.0
* npm version:  4.2.0
* os: mac

### Error output
 ~/code/javascript  learnyounode
module.js:472
    throw err;
    ^

Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/learnyounode/node_modules/readable-stream/lib/_stream_readable.js:6:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

### My Code
```js
 // copy your code here
```

**Comment by adminamp** [comment]
Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_readable.js:6:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by adminamp** [comment]
i have some serious issues to install nap nodes and I don t know if it s a problem with mac os or not ??
