### ISSUE TITLE
Juggling async learnyounode

### ISSUE THREAD

**Issue by locdoan12121997** [nodeschool/discussions#2108]
I don't know where did I go wrong. I checked carefully the error but can't still understand. And btw, I use http.get() as call back function to make sure response from each server must complete in order. Will this way work.

node version: v6.7.0
npm version:  3.10.3
os: windows 10

### Error output
```
 C:\Users\win\Desktop\Node js\Nodeschool\learnyounode\juggling-async.js:6
      res2.pipe(bl(function(err,data2)));
                                      ^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

Your submission results compared to the expected:

────────────────────────────────────────────────────────────────────────────────

1.  ACTUAL:    ""
1.  EXPECTED:  "Stands out like a chuck a sickie my trent from punchy coldie. Gutful of stickybeak mate watch out for the slab. She'll be right banana bender piece of piss lets get some slaps. Stands out like a dead horse flamin he's got a massive hooroo. As dry as a battler bloody he hasn't got a mullet. "

2.  ACTUAL:
2.  EXPECTED:  "He's got a massive gobsmacked to we're going muster. You little ripper holy dooley! to gutful of chrissie. Watch out for the budgie smugglers piece of piss lets get some grundies. You little ripper jillaroo flamin as dry as a shag on a rock. "

3.  ACTUAL:
3.  EXPECTED:  "Lets throw a vinnie's mate trent from punchy relo. Stands out like a bikkie also as cross as a flanno. She'll be right gone walkabout with stands out like a chunder. Trent from punchy amber fluid also lets throw a mates. Grab us a cream bloody we're going joey. "

4.  ACTUAL:
4.  EXPECTED:  ""
```

### My Code
```js
 var bl = require('bl');
var http = require('http');
http.get(process.argv[2], function (res) {
  http.get(process.argv[3], function (res1){
    http.get(process.argv[4], function (res2){
      res2.pipe(bl(function(err,data2)))
    })
    res1.pipe(bl(function(err,data1)))
  })
  res.pipe(bl(function(err,data){
    console.log(data.toString());
    console.log(data1.toString());
    console.log(data2.toString());
  }))
}).on('error', function(e) {
  console.log("Got error: " + e.message);
});

```

**Comment by davecocoa** [comment]
The error you're seeing is because a valid function expression is composed of:
- the keyword `function` followed by
- a pair of parentheses `()` optionally containing a list of parameters for example `(param1, param2)` followed by
- a pair of curly brackets `{}` containing the function body.

[More on function expressions can be read on the mozilla developer network](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/function).

In your code, you have `function(err,data2)` without a pair of curly brackets containing the function body.
