### ISSUE TITLE
Learnyounode My First Async I/O! error when running

### ISSUE THREAD

**Issue by ajdickey** [nodeschool/discussions#2125]
* node version: v6.2.2
* npm version: 3.9.5
* os: mac 10.12.5

I have my doubts about whether my code will work, but I haven't been able to get past this error, regardless, which seems like it may originate from outside my code. Any help would be hugely appreciated! I've Googled to no avail.

### Error output
```
fs.js:297
  binding.open(pathModule._makeLong(path),
          ^

TypeError: path must be a string or Buffer
    at TypeError (native)
    at Object.fs.readFile (fs.js:297:11)
    at count_lines (/Users/user/Desktop/LearnNode/learnyounode/my_first_async_io.js:10:5)
    at Object.<anonymous> (/Users/user/Desktop/LearnNode/learnyounode/my_first_async_io.js:24:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
```

### My Code
```js
process.argv;

var fs = require('fs');

var file_buf = fs.readFile(process.argv[2]);

var lines = undefined

function count_lines(callback){
	fs.readFile(file_buf, 'utf8', function doneReading(err, fileContents){
		if (err){
			console.log(err)
		} else {
			lines = fileContents.split('\n')
			callback()
		}
	})
}

function logMyLines(){
	console.log(lines)
}

count_lines(logMyLines)
```

**Comment by davecocoa** [comment]
Hi,

When reading errors, it's worth checking each line of the call stack (all those lines starting with "at...") to see if any of them refer to files you control. In this case, I can see two lines relating to your files:
```
    at count_lines (/Users/user/Desktop/LearnNode/learnyounode/my_first_async_io.js:10:5)
    at Object.<anonymous> (/Users/user/Desktop/LearnNode/learnyounode/my_first_async_io.js:24:1)
```
It's often the highest line of the call stack which gives the most useful information, checking line 10 of your file we see:
```
	fs.readFile(file_buf, 'utf8', function doneReading(err, fileContents){
```
Combining this line with the error message `path must be a string or Buffer` and the [`fs.readFile` docs](https://nodejs.org/api/fs.html#fs_fs_readfile_path_options_callback), I wonder what the value of `file_buf` is? Perhaps you could check using `console.log` and continue debugging from there.

Good luck!

**Comment by ajdickey** [comment]
Thanks so much, @davecocoa! With that guidance, I was able to get it up and running :)
