### ISSUE TITLE
Can't run learnyounode, but was able to run a different workshop

### ISSUE THREAD

**Issue by Meaix88** [nodeschool/discussions#2139]
Apologies if I'm not doing this right...I'm pretty new to programming in general (just started this summer and went through all of MDN's tutorials on html, css, and javascript before I was directed to nodeschool). I was able to get the workshop on scopes and closures to run no problem and completed the entire thing. Then I installed the learnyounode workshop the same way I did the scope workshop and it all goes nutty. I have attached an image of what I am seeing in the command prompt immediately below, but I also copy/pasted the laundry list of error/warning messages further down below the version information in text. The last lines said "npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\meaix\Dropbox\My Files\website-development\octo-infinitus\npm-debug.log", but I couldn't find that dubug log file at the path location it references. Any suggestions would be much appreciated! I hear good things about the workshops in nodeschool and the scope workshop seemed pretty good. Thanks!

![image](https://user-images.githubusercontent.com/11046720/28436597-b7d28612-6d54-11e7-96f7-e4b351ce2832.png)

### If you have a problem with an error message:

* node version: v6.11.1
* npm version:  3.10.10
* os: windows 10 pro

### Error output
```
 // copy your error output here
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:14:12)
npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:69:19)
npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:81:29)
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:90:16
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15)
npm WARN addRemoteGit  codeclimate/javascript-test-reporter#97f1ff2cf18cd5f03191d3d53e671c47e954f2fa resetting remote C:\Users\meaix\AppData\Roaming\npm-cache\_git-remotes\git-github-com-codeclimate-javascript-test-reporter-git-97f1ff2cf18cd5f03191d3d53e671c47e954f2fa-fb9afbfa because of error: { Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:14:12)
npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:69:19)
npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:81:29)
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:90:16
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOGIT' }
npm ERR! git clone --template=C:\Users\meaix\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/codeclimate/javascript-test-reporter.git C:\Users\meaix\AppData\Roaming\npm-cache\_git-remotes\git-github-com-codeclimate-javascript-test-reporter-git-97f1ff2cf18cd5f03191d3d53e671c47e954f2fa-fb9afbfa: undefined
npm ERR! git clone --template=C:\Users\meaix\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/codeclimate/javascript-test-reporter.git C:\Users\meaix\AppData\Roaming\npm-cache\_git-remotes\git-github-com-codeclimate-javascript-test-reporter-git-97f1ff2cf18cd5f03191d3d53e671c47e954f2fa-fb9afbfa: undefined
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:14:12)
npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:69:19)
npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:81:29)
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:90:16
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15)
npm WARN addRemoteGit  codeclimate/javascript-test-reporter#97f1ff2cf18cd5f03191d3d53e671c47e954f2fa resetting remote C:\Users\meaix\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-codeclimate-javascript-test-reporter-git-97f1ff2cf18cd5f03191d3d53e671c47e954f2fa-52c33c88 because of error: { Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:14:12)
npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:69:19)
npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:81:29)
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:90:16
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOGIT' }
npm ERR! git clone --template=C:\Users\meaix\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/codeclimate/javascript-test-reporter.git C:\Users\meaix\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-codeclimate-javascript-test-reporter-git-97f1ff2cf18cd5f03191d3d53e671c47e954f2fa-52c33c88: undefined
npm ERR! git clone --template=C:\Users\meaix\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/codeclimate/javascript-test-reporter.git C:\Users\meaix\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-codeclimate-javascript-test-reporter-git-97f1ff2cf18cd5f03191d3d53e671c47e954f2fa-52c33c88: undefined
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:14:12)
npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:69:19)
npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:81:29)
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:90:16
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15)
npm WARN addRemoteGit  codeclimate/javascript-test-reporter#97f1ff2cf18cd5f03191d3d53e671c47e954f2fa resetting remote C:\Users\meaix\AppData\Roaming\npm-cache\_git-remotes\git-github-com-codeclimate-javascript-test-reporter-git-97f1ff2cf18cd5f03191d3d53e671c47e954f2fa-09390dad because of error: { Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:14:12)
npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:69:19)
npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:81:29)
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:90:16
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOGIT' }
npm ERR! git clone --template=C:\Users\meaix\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:codeclimate/javascript-test-reporter.git C:\Users\meaix\AppData\Roaming\npm-cache\_git-remotes\git-github-com-codeclimate-javascript-test-reporter-git-97f1ff2cf18cd5f03191d3d53e671c47e954f2fa-09390dad: undefined
npm ERR! git clone --template=C:\Users\meaix\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:codeclimate/javascript-test-reporter.git C:\Users\meaix\AppData\Roaming\npm-cache\_git-remotes\git-github-com-codeclimate-javascript-test-reporter-git-97f1ff2cf18cd5f03191d3d53e671c47e954f2fa-09390dad: undefined
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "learnyounode"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\meaix\Dropbox\My Files\website-development\octo-infinitus\npm-debug.log
```

### My Code
```js
 // copy your code here
im just typing the workshopper name into the command line like i did with a different workshop that I was able to complete successfully. I tried typing it in by hand and copy/pasting it just to make sure I wasn't making any mistakes

```

**Comment by gorhgorh** [comment]
Hi there, it seems that you don't have git installed on this machine hence the error ```npm ERR! not found: git``` please try ```git --version``` in a terminal and see if it gives a version number or an error. 

If it gives an error in past nodeschool we used an alternative to the window cmd.exe called [cmder](http://cmder.net/) if you download the full version it comes with git for windows installed, so download/install it, and use it to install this workshoper. 

you can also install [git for windows](https://git-for-windows.github.io/) if you want to keep your command line.
