### ISSUE TITLE
npm test

### ISSUE THREAD

**Issue by Tourzie** [nodeschool/discussions#2151]
am stuck on npm testing verify and package niceties
 "name": "nodejstutorials",
  "version": "1.0.1",
  "main": "index.js",
  "scripts": {
    "test": "node test.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {},
  "devDependencies": {},
  "description": ""
}

error when running npm 
SyntaxError: Unexpected token :
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
npm ERR! Test failed.  See above for more details.

**Comment by stefanmirck** [comment]
Hi @Tourzie, can you explain a little bit more what it is you’re trying to do?

**Comment by Tourzie** [comment]
I am on camp called freecodecamp and we are asked to do this task about managing packages with npm and the part am struggling with is npm test on the task
