### ISSUE TITLE
javascripting for loop exercise

### ISSUE THREAD

**Issue by brandonsamuel1** [nodeschool/discussions#2193]
### Notes

can someone please tell me what happened...? And how to fix. 

JAVASCRIPTING

## FOR LOOP (Exercise 10 of 19)

{ Error: Command failed: node "/vagrant/javascripting/for-loop.js"
/vagrant/javascripting/for-loop.js:4
for (var i = 0; i < limit; i ++ total += i) {
                                ^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node "/vagrant/javascripting/for-loop.js"' }
vagrant [javascripting]> javascripting verify for-loop.js

# JAVASCRIPTING

## FOR LOOP (Exercise 10 of 19)

javascripting verify for-loop.js
javascripting
vagrant

**Comment by brandonsamuel1** [comment]
if you look at the bottom, whenever i type javascripting, nothing happens anymore

**Comment by brandonsamuel1** [comment]
disregard this, got it working!
