### ISSUE TITLE
Stuck on Exercise 6

### ISSUE THREAD

**Issue by trueivorian** [nodeschool/discussions#2202]
### Error output
```
 Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   "CHANGELOG.md"                      ==    "CHANGELOG.md"                     
   "LICENCE.md"                        ==    "LICENCE.md"                       
   "README.md"                         ==    "README.md"                        
   ""                                  ==    ""                                 

────────────────────────────────────────────────────────────────────────────────

 ✓ 

 Submission results match expected

Error: testing
    at Exercise.validateModule (/usr/local/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:12:15)
    at Exercise.verifyModuleUsed (/usr/local/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:207:18)
    at Exercise.verify (/usr/local/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:219:20)
    at Exercise.<anonymous> (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:40:8)
    at next (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:188:19)
    at /usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:195:7
    at /usr/local/lib/node_modules/learnyounode/node_modules/workshopper-wrappedexec/wrappedexec.js:56:9
    at FSReqWrap.oncomplete (fs.js:135:15)
 ✓ 

 Additional module file exports a single function

 ✓ 

 Additional module file exports a function that takes 3 arguments

 ✗ 

 Your additional module file [MakeItModularPart1.js] does not appear to
 pass back an error received from fs.readdir(). Use the following idiomatic
 Node.js pattern inside your callback to fs.readdir(): if (err) return
 callback(err)

 # FAIL Your solution to MAKE IT MODULAR didn't pass. Try again!

```

### My Code
```js
 module.exports = function makeItModular(path, ext, callback){
  var fs = require('fs')

  var err = undefined

  var arr = new Array()

  function readList(err, callback){

    fs.readdir(path, function doneReading(err, arr){
      if(err){
        return console.log(err)
      }

      for(var i=0; i<arr.length; i++){
        var pattern = ".+" + ext + "$"
        if(arr[i].match(new RegExp(pattern))){
          console.log(arr[i])
        }
      }
    })

    callback()
  }

  function printList(){
    for(var i=0; i<arr.length; i++){
      console.log(arr.get(i))
    }
  }

  readList(err, printList)

  callback(err, arr)
}

```

**Comment by trueivorian** [comment]
Also any feedback on good JavaScript practice would be much appreciated

**Comment by froziq** [comment]
Hi!
you need to send callback with error if fs.readdir end with error:
write 
```
if(err){
  return callback(err)
}
```
instead
```
if(err){
  return console.log(err)
}
```

it should help
