### ISSUE TITLE
MAKE IT MODULAR Error: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by sciblo** [nodeschool/discussions#2230]
Help me please. What i did not right?

**## Output**

```
ИЗУЧАЙТЕ NODE.JS!

MAKE IT MODULAR (Задача 6 из 13)

Сравнение результатов решения c ожидаемыми результами:

               ПОЛУЧЕННЫЙ                              ОЖИДАЕМЫЙ
────────────────────────────────────────────────────────────────────────────────

   "CHANGELOG.md"                      ==    "CHANGELOG.md"
   "LICENCE.md"                        ==    "LICENCE.md"
   "README.md"                         ==    "README.md"
   ""                                  ==    ""

────────────────────────────────────────────────────────────────────────────────

 ✓

 Результат совпал с ожидаемым

 ✓

 Файл с дополнительным модулем экспортирует функцию

 ✓

 Файл с дополнительным модулем экспортирует функцию, которая принимает 3
 аргументов

 ✓

 Файл с дополнительным модулем корректно обработал ошибку

 ✓

 Файл с дополнительным модулем корректно обработал функцию обратного вызова

C:\Users\Константин\AppData\Roaming\npm\node_modules\learnyounode\node_modules\workshopper-exercise\exercise.js:188
    processors[i].call(self, mode, function (err, pass) {
                  ^

TypeError: Cannot read property 'call' of undefined
    at next (C:\Users\Константин\AppData\Roaming\npm\node_modules\learnyounode\node_modules\workshopper-exercise\exercise.js:188:19)
    at C:\Users\Константин\AppData\Roaming\npm\node_modules\learnyounode\node_modules\workshopper-exercise\exercise.js:195:7
    at callback (C:\Users\Константин\AppData\Roaming\npm\node_modules\learnyounode\exercises\make_it_modular\verify.js:26:15)
    at modFileError (C:\Users\Константин\AppData\Roaming\npm\node_modules\learnyounode\exercises\make_it_modular\verify.js:31:5)
    at C:\Users\Константин\AppData\Roaming\npm\node_modules\learnyounode\exercises\make_it_modular\verify.js:131:18
    at doneReading (C:\Users\Константин\Desktop\Материалы для занятий по вёрстке сайтов\NodeSchool\learnyounode\module.js:14:5)
    at FSReqWrap.oncomplete (fs.js:149:15)
```

**program.js:**

```js
var module = require('./module.js');

var callback = (err, data) => err ? console.log("There's an error") : console.log(data);

module(process.argv[2], process.argv[3], callback);

```

**module.js:**

```js
var fs = require('fs');
var path = require('path');

module.exports = function makeModule(dir, format, callback) {

	fs.readdir(dir, function doneReading(err, list) {

		if (err) 
			return callback(err);
		
		// do something with the fileContents
		for (var i = 0; i < list.length; i++) {
			if (path.extname(list[i]) === "." + format) {
				callback(null, list[i]);
			}
		}
		
	});

};

```

**Comment by noffle** [comment]
The error isn't at all helpful, but reread this paragraph from the instructions:

```
  The callback function must be called using the idiomatic node(err, data)  
  convention. This convention stipulates that unless there's an error, the  
  first argument passed to the callback will be null, and the second will be  
  your data. In this exercise, the data will be your filtered list of files,  
  as an Array.
```

Are you calling `callback` exactly once with a list of results?

**Comment by sciblo** [comment]
I don't understand. I use
**program.js:**
```js
...
var callback = (err, data) => err ? console.log("There's an error") : console.log(data);
...
```
and
**module.js:**
```js
...
if (err) 
    return callback(err);
else
    ...
    callback(null, list[i]);
    ...
...
```
It is not right? Or are you telling me about something else?

**Comment by noffle** [comment]
Hey @sciblo, see this code here:

```js
		for (var i = 0; i < list.length; i++) {
			if (path.extname(list[i]) === "." + format) {
				callback(null, list[i]);
			}
		}
```
Some questions:

1. If, say, there are three matches for the desired extension, how many times will `callback` be run? Node-style callbacks are intended to only ever be called *once*.
2. The instructions ask for an *array* from the callback. What data type is `list[i]`?

**Comment by sciblo** [comment]
@noffle 
I think:
1. `callback` will be run 3 times.
2. `list[i]` data type is String.
Sorry, if I wrong understand you.

**Comment by noffle** [comment]
@sciblo Yep, that's right. Now consider this:

1. Node-style callbacks should only ever be run once.
2. The exercise instructions ask for the module to return an Array through the callback.

**Comment by sciblo** [comment]
@noffle Ok, but if i return in callback array i will have this:
`[ 'CHANGELOG.md', 'LICENCE.md', 'README.md' ]`
and this no right
```
Сравнение результатов решения c ожидаемыми результами:

               ПОЛУЧЕННЫЙ                              ОЖИДАЕМЫЙ
────────────────────────────────────────────────────────────────

   "[ 'CHANGELOG.md', 'LICENCE.md', 'README.md' ]" !=    "CHANGELOG.md"
   ""                                  !=    "LICENCE.md"
                                       !=    "README.md"
                                       !=    ""

────────────────────────────────────────────────────────────────
```

**Comment by noffle** [comment]
From the exercise instructions:

```
   Print the list of files (one file per line) to the console.
```

In general, when stuck, it's useful to read over the instructions again to see if you misunderstood some part of what was asked for.

**Comment by sciblo** [comment]
@noffle Thank you, I understand, I try to doing this.

**Comment by sciblo** [comment]
@noffle Yeah, i doing this!
