### ISSUE TITLE
js-best-practices Verify Your Full Vending Machine Implementation errors

### ISSUE THREAD

**Issue by AllisonLittman3** [nodeschool/discussions#2252]
I may be WAY off the boat here, but I'm struggling to get through the last part of this tutorial (js-best-practices). Does anyone have a more descriptive answer for my difficulties? I can't get my code to verify. What needs to be in the vendingMachine file? Thank you for your help!

### Error output
```
  1) "before each" hook for "vendingMachine should have a function called insertCoin"

  0 passing (4ms)
  1 failing

  1)  "before each" hook for "vendingMachine should have a function called insertCoin":
     Error: Invalid Input
      at Object.canAfford (javascripting/balanceManager.js:17:15)
      at Object.decreaseBalance (javascripting/balanceManager.js:22:14)
      at Object.releaseChange (javascripting/vendingMachine.js:22:20)
      at Context.<anonymous> (/usr/local/lib/node_modules/js-best-practices/exercises/verify_vendingmachine/exercise.js:14:20)
```

### My Code
```js
var balanceManager = require('./balanceManager');
var changeHandler = require('./changeHandler');
var productInventory = require('./productInventory');

module.exports = {

  insertCoin: function(coinType){
    var value = changeHandler.getAmount(coinType);
    balanceManager.increaseBalance(value);
  },

  isValidAmount: function(amount){
    if(amount === null){
      return false;
    } else {
      return true;
    }
  },

  releaseChange: function(){
    var currentBalance = balanceManager.getBalance();
    balanceManager.decreaseBalance(currentBalance);
    return changeHandler.convertToChange(currentBalance);
  },

  vendProduct: function(productId){
    var product = productInventory.getProduct(productId);
    balanceManager.decreaseBalance(product.price);
    return product;
  }

};

**Comment by finnp** [comment]
Hey, not sure what the problem is. Could you comment the code of the other files especially `balanceManager` as well?
