### ISSUE TITLE
Juggling Async Problems

### ISSUE THREAD

**Issue by 1234filip** [nodeschool/discussions#2275]
### If you have a problem with an error message:

* node version: v9.0.0
* npm version: 5.6.0
* os: Windows 10

### Error output
```
D:\Projects\TestingStuff\LearnYouNode\JugglingAsync\app.js:14
    response.on('data', function (data) {
    ^

ReferenceError: response is not defined
    at ClientRequest.<anonymous> (D:\Projects\TestingStuff\LearnYouNode\JugglingAsync\app.js:14:5)
    at Object.onceWrapper (events.js:324:30)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:550:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
    at Socket.socketOnData (_http_client.js:439:20)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at addChunk (_stream_readable.js:265:12)
```

### My Code
```js
const http = require('http');
const url1 = process.argv[2];
const url2 = process.argv[3];
const url3 = process.argv[4];
const urls = new Array(url1, url2, url3);
let arr = new Object();

const get = function (url, counter) {
  http.get(url, function (reposnse) {
    let final = '';
    reposnse.setEncoding('utf8');
    response.on('data', function (data) {
      final += data;
    });
    response.on('end', () => {
      arr[ur] = final;
      if (cnt === 3) {
        console.log('done');
      }
    })
  });
}

for (let i = 0; i < 3; i++) {
  get(urls[i], i);
}
```

**Comment by WaleedAshraf** [comment]
There is a typo: reposnse
