### ISSUE TITLE
Hello There!

### ISSUE THREAD

**Issue by mjaracz** [nodeschool/discussions#2290]
My error, and problems looks like this 
```
TypeError: callback is not a function
    at module.exports (C:\Users\micha\Documents\nodeschool\modules-exercises\module.js:25:9)
    at fs.readdir (C:\Users\micha\Documents\nodeschool\modules-exercises\readdir.js:14:9)
    at FSReqWrap.oncomplete (fs.js:135:15)
```
And  kod for broken moduls looks like this..

```
const path = require('path');
const ext = "." + process.argv[3];
ext.toString();

function callback(date) {
    const filterArr = date.filter((item) => {
        
        const extname = (path.extname(item).toString() === ext) ? true : false;
        
        if(extname) {
            return item
        }
    })
}


module.exports = function(err, date, callback) {
    if(err) {
        console.log(err);
    }
    else {
        callback(date);
    }
}

```
Do you have some ideas why console return this type of error ? 
Best regards and thenks for every respons. :)

**Comment by mjaracz** [comment]
Ok I work of this problem and I have finily solving. 
This is my solving 
```
const path = require('path');

const ext = "." + process.argv[3];
ext.toString();

const callback = function(err, date) {
    if(err) {
        console.log(err);
    } 
    else {
        const filterArr = date.filter((item) => {
            const extname = (path.extname(item).toString() === ext) ? true : false;
            
            if(extname) {
                return item
            }
        })


        filterArr.forEach(item => {
            return console.log(item);
        });
    }
};

module.exports =  (err, date) => {
    if(err) {
        return callback(err, null)
    }
    else {
        return callback(null, date);
    }
};
```

But unfortunately This is not enought to pass test of my program, becouse in this excersise nodeyoulearn returne something like this..

```

 Your additional module file [module.js] exports a function that takes
 fewer than three arguments. You must accept a directory, a filter and a
 callback.

```
Do we have some idea How fixed this ?
