### ISSUE TITLE
Missing module in learnyoureact?

### ISSUE THREAD

**Issue by laserblue** [nodeschool/discussions#2295]
I am using an app called Dory Node for Android. The Node School javascripting workshop worked well but learnyoureact is giving me trouble stating that the babel/register module can't be found.I checked the module folder and I can't find it either. 
   I had a problem with a syntax error with _dirname in program.js and I changed app.use from '/' to my learnyoureact directory with path 'storage/emulated/0/learnyoureact/' so I am not sure the program has a correct path. 

##Output

module.js:471
    throw err;
    ^

Error: Cannot find module 'babel/register'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/storage/emulated/0/learnyoureact/program.js:9:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
✗

**Comment by Jiasm** [comment]
did you run `npm install babel-register --save-dev` in terminal? try it.

**Comment by laserblue** [comment]
I tried it. The npm-debug.log runs from 14007 to 23174. From 23151-23174 is a list of errors.
