### ISSUE TITLE
scope-chains-closures ERR

### ISSUE THREAD

**Issue by Slick3gz** [nodeschool/discussions#2309]
* node version: v10.1.0
* npm version:  6.0.1
* os: windows 7

### Error output
```


    SCOPE-CHAINS-CLOSURES
    ---------------------
    1. Scopes
    2. Scope Chains
    3. Global Scope & Shadowing
    4. Closures
    5. Garbage Collection
    -----------------
    HELP
    EXIT


fs.js:140
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:140:9)
    at Object.fs.writeFile (fs.js:1258:14)
    at Shop.save (C:\Users\udchstore\AppData\Roaming\npm\node_modules\scope-chai
ns-closures\node_modules\adventure\index.js:288:8)
    at Shop.select (C:\Users\udchstore\AppData\Roaming\npm\node_modules\scope-ch
ains-closures\node_modules\adventure\index.js:246:10)
    at EventEmitter.<anonymous> (C:\Users\udchstore\AppData\Roaming\npm\node_mod
ules\scope-chains-closures\node_modules\adventure\index.js:278:14)
    at EventEmitter.emit (events.js:182:13)
    at Menu.<anonymous> (C:\Users\udchstore\AppData\Roaming\npm\node_modules\sco
pe-chains-closures\node_modules\adventure\lib\menu.js:49:22)
    at Menu.emit (events.js:182:13)
    at Menu.ondata [as _ondata] (C:\Users\udchstore\AppData\Roaming\npm\node_mod
ules\scope-chains-closures\node_modules\terminal-menu\index.js:215:18)
    at DestroyableTransform._transform (C:\Users\udchstore\AppData\Roaming\npm\n
ode_modules\scope-chains-closures\node_modules\terminal-menu\index.js:50:18)
```

Getting this error output when selecting an option on the menu.

**Comment by br1code** [comment]
same error here, i think is because v10 of node

**Comment by Sceat** [comment]
yup 
```
fs.js:159
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:159:9)
    at Object.fs.writeFile (fs.js:1278:14)
    at Shop.save (/usr/lib/node_modules/scope-chains-closures/node_modules/adventure/index.js:288:8)
    at Shop.select (/usr/lib/node_modules/scope-chains-closures/node_modules/adventure/index.js:246:10)
    at EventEmitter.<anonymous> (/usr/lib/node_modules/scope-chains-closures/node_modules/adventure/index.js:278:14)
    at EventEmitter.emit (events.js:182:13)
    at Menu.<anonymous> (/usr/lib/node_modules/scope-chains-closures/node_modules/adventure/lib/menu.js:49:22)
    at Menu.emit (events.js:182:13)
    at Menu.ondata [as _ondata] (/usr/lib/node_modules/scope-chains-closures/node_modules/terminal-menu/index.js:215:18)
    at DestroyableTransform._transform (/usr/lib/node_modules/scope-chains-closures/node_modules/terminal-menu/index.js:50:18)
``` 
on Node `v10.4.0`
