### ISSUE TITLE
Exercice 5 - problem with exercise.js

### ISSUE THREAD

**Issue by Luisandremp** [nodeschool/discussions#2315]
Hello there, I'm having an issue in Exercise 5:
in node_modules\workshopper-exercise\exercise.js file and I'm not sure if the issue comes from my code or not, is there something I'm doing wrong? is it a version problem? something else?

Thank you for the tutorials!

node v8.11.2
npm v5.6.0
windows 10

### Error output
```
# LEARN YOU THE NODE.JS FOR MUCH WIN!

## MAKE IT MODULAR (Exercise 6 of 13)


Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED
────────────────────────────────────────────────────────────────────────────────

   "CHANGELOG.md"                      ==    "CHANGELOG.md"
   "LICENCE.md"                        ==    "LICENCE.md"
   "README.md"                         ==    "README.md"
   ""                                  ==    ""

────────────────────────────────────────────────────────────────────────────────

 ✓

 Submission results match expected

 ✓

 Additional module file exports a single function

 ✓

 Additional module file exports a function that takes 3 arguments

 ✓

 Additional module file handles errors properly

 ✓

 Additional module file handles callback argument

C:\Users\Luis Andre\AppData\Roaming\npm\node_modules\learnyounode\node_modules\workshopper-exercise\exercise.js:188
    processors[i].call(self, mode, function (err, pass) {
                  ^

TypeError: Cannot read property 'call' of undefined
    at next (C:\Users\Luis Andre\AppData\Roaming\npm\node_modules\learnyounode\node_modules\workshopper-exercise\exercise.js:188:19)
    at C:\Users\Luis Andre\AppData\Roaming\npm\node_modules\learnyounode\node_modules\workshopper-exercise\exercise.js:195:7
    at callback (C:\Users\Luis Andre\AppData\Roaming\npm\node_modules\learnyounode\exercises\make_it_modular\verify.js:26:15)
    at modFileError (C:\Users\Luis Andre\AppData\Roaming\npm\node_modules\learnyounode\exercises\make_it_modular\verify.js:31:5)
    at C:\Users\Luis Andre\AppData\Roaming\npm\node_modules\learnyounode\exercises\make_it_modular\verify.js:131:18
    at C:\wamp64\www\nodeTest\moduleEx05.js:11:4
    at Array.forEach (<anonymous>)
    at C:\wamp64\www\nodeTest\moduleEx05.js:9:10
    at FSReqWrap.oncomplete (fs.js:135:15)

```

### My Code
```js
    const myModule = require('./moduleEx05');

    const folder = process.argv[2]
    const ext = process.argv[3]
    let results = new Array(0);

    myModule(folder, ext, function (err, file){
    	if (err) return callback(err);
    		console.log(file)
    });
```
Module:

```js
module.exports = function (dir, extension, callback){
	const fs = require('fs')
	const path = require('path')
	const folder = dir;
	const ext = '.' + extension;
	fs.readdir(folder, function (err, files) {
	  if (err) return callback(err);

	  files.forEach(function (file) {
	    if (path.extname(file) === ext) {
			callback(null, file);
	    }
	  })
	})	
}
```

**Comment by willybeans** [comment]
My best guess is with this: 
`    myModule(folder, ext, function (err, file){
    	if (err) return **callback(err);**
    		console.log(file)
    });`
