### ISSUE TITLE
Issue with a loop exercise javascript

### ISSUE THREAD

**Issue by NosretepKire** [nodeschool/discussions#2346]
### Notes

**Please delete this section after reading it**

### If you have a problem with an error message:

* node version: <run "node -v" in you terminal and replace this>
* npm version:  <run "npm -v" in you terminal and replace this>
* os: windows 7/windows 10/mac/linux

### Error output
```
{ Error: Command failed: node "/vagrant/javascripting/for-loop.js"
/vagrant/javascripting/for-loop.js:3
for (i = 0, i < 10, i++) {
                       ^

SyntaxError: Unexpected token )
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node "/vagrant/javascripting/for-loop.js"' }

```

### My Code
```js
var total = 0;
var limit = 10;
for (i = 0, i < 10, i++) {
  total += i;
  console.log(total)
};

```

**Comment by davecocoa** [comment]
In a javascript for loop, the initializer, condition and increment should be separated by semi colons (`;`), not commas (`,`), so instead of `for (i = 0, i < 10, i++) {`, try `for (i = 0; i < 10; i++) {`
