### ISSUE TITLE
Challenge #14 problems using for-loop

### ISSUE THREAD

**Issue by 0theRookie** [nodeschool/discussions#2362]
Here is my attempt:

**_var pets = ['cat', 'dog', 'rat'];

for(var i = 0, i < pets.length, i++ ){
  pets[i] = pets[i] + 's'
 };

console.log(pets);_**

When I go to verify, I get an error complaining about my < symbol:

**_{ Error: Command failed: node "/vagrant/javascripting/looping-through-arrays.js"
/vagrant/javascripting/looping-through-arrays.js:4
for(var i = 0, i < pets.length, i++ ){
                 ^

SyntaxError: Unexpected token <
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node "/vagrant/javascripting/looping-through-arrays.js"' }_**

Not sure what I'm missing, because i needs to be < pets.length in order for the loop to stop after the final string right?

**Comment by AnshuPrince** [comment]
Hey,i guess you have a minor syntax error in your for loop.you need to separate your expressions of for loop using semicolon(;) whereas you are using comma(,).
for(var i=0;i<pets.length;i++){
}
