### ISSUE TITLE
stream-adventure crashes when I select BEEP BOOP menu item

### ISSUE THREAD

**Issue by robert-barcelona** [nodeschool/discussions#2407]
### If you have a problem with an error message:
I installed 'stream-adventure' (` npm install -g stream-adventure`) and start it up.  When I select the first menu item (or the second), "BEEP BOOP", 'stream-adventure' crashes immediately.

* node version: v10.8.0
* npm version: 6.9.0
* os: MacOS 10.13.6

### Error output

```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: shutdown ENOTCONN
    at ReadStream.Socket._final (net.js:369:25)
    at callFinal (_stream_writable.js:612:10)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
### My Code
```

**Comment by robert-barcelona** [comment]
One needs an earlier version of Node.  It would be nice if it were updated to work with the latest.
