### ISSUE TITLE
Stuck on exercise 'MY FIRST ASYNC I/O! (Exercise 4 of 13)'

### ISSUE THREAD

**Issue by pamnanaimanish169** [nodeschool/discussions#2423]
### If you have a problem with an error message:

* node version: <v10.15.3s>
* npm version:  <6.4.1>
* os: 0windows 10/mac/linux

### Error output
```
C:\Users\Manish\Desktop\learnyounoe\program.js:24
        var text = fs.readFile('C:\/Users\/Manish\/Desktop\/learnyounoe\/program2.txt') {
                                                                                        ^

SyntaxError: Unexpected token {
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
```

### My Code
```js
function addnewLine( callback ) {
	var text = fs.readFile('C:\/Users\/Manish\/Desktop\/learnyounoe\/program2.txt') {
		callback();
	})
}

function newlines_count() {
	var lines = text.split('\n');
	var newlines_count = lines.length - 1;
	console.log(newlines_count);
}

newlines_count( addNewLines );
```

**Comment by reallygeek** [comment]
SPOILER:
here's the official result

>  var fs = require('fs')
> 
>     var contents = fs.readFileSync(process.argv[2])
>     var lines = contents.toString().split('\n').length - 1
>     console.log(lines)
> 
>     // note you can avoid the .toString() by passing 'utf8' as the
>     // second argument to readFileSync, then you'll get a String!
>     //
>     // fs.readFileSync(process.argv[2], 'utf8').split('\n').length - 1

here's what worked for me,

> var fs = require('fs');
> var buf =fs.readFileSync(process.argv[2])
> var str = buf.toString();
> var lines = str.split('\n');
> var n = lines.length-1;
> console.log(n);
