### ISSUE TITLE
Javascripting  Functions Ex 18 of 20 (Error: Command failed)

### ISSUE THREAD

**Issue by YamadaKY** [nodeschool/discussions#2478]
### If you have a problem with an error message:

* node version: v12.14.1
* npm version:  6.13.7
* os: mac OS 10.15.3

### Error output
# JAVASCRIPTING

## FUNCTIONS (Exercise 18 of 20)

Error: Command failed: node "/Users/*MyName*/javascripting/function.js"

 // copy your error output here
```
Error: Command failed: node "/Users/*MyName*/javascripting/function.js"
/Users/*MyName*/javascripting/function.js:4
console.log(eat(bananas));
                ^

ReferenceError: bananas is not defined
    at Object.<anonymous> (/Users/*MyName*/javascripting/function.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:223:5)
    at Pipe.<anonymous> (net.js:664:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node "/Users/*MyName*/javascripting/function.js"'
}

### My Code
function.js
 // copy your code here
function eat(food){
    return food + 'tasted really good.';
}
console.log(eat(bananas));

**Comment by danjmaster** [comment]
The error is `ReferenceError: bananas is not defined`
You either need to define `bananas`, or pass it to the function as a string.

**Comment by YamadaKY** [comment]
Thank you for answering.
