### ISSUE TITLE
Problem with `scope` exercise when using backticks

### ISSUE THREAD

**Issue by illyric** [nodeschool/discussions#2485]
### Notes

* node version: v11.15.0
* npm version:  6.7.0
* os: mac

### Error output
```
❯ javascripting verify scope.js

# JAVASCRIPTING

## SCOPE (Exercise 20 of 20)

{ Error: Command failed: node "/Users/i.kosumi/dev/learn/javascripting/scope.js"
/Users/i.kosumi/dev/learn/javascripting/scope.js:11
    (function thirdFunction () {
    ^

TypeError: console.log(...) is not a function
    at secondFunction (/Users/i.kosumi/dev/learn/javascripting/scope.js:11:5)
    at firstFunction (/Users/i.kosumi/dev/learn/javascripting/scope.js:18:5)
    at Object.<anonymous> (/Users/i.kosumi/dev/learn/javascripting/scope.js:19:3)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11

    at ChildProcess.exithandler (child_process.js:299:12)
    at ChildProcess.emit (events.js:193:13)
    at maybeClose (internal/child_process.js:999:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node "/Users/i.kosumi/dev/learn/javascripting/scope.js"'
```

### My Code
```js
 const a = 1; const b = 2; const c = 3;

(function firstFunction () {
  const b = 5; const c = 6;

  (function secondFunction () {
    const b = 8;
//      console.log('a: ' + a + ', b: ' + b + ', c: ' + c); uncommenting this line and commenting the line below does work.
      console.log(`a: ${a}, b: ${b}, c: ${c}`)

    (function thirdFunction () {
      const a = 7; const c = 9;

      (function fourthFunction () {
        const a = 1; const c = 8
      })()
    })()
  })()
})()
```

**Comment by illyric** [comment]
I already found out the problem. For some reasons (which I don't know) a semicolon is required at the end of the `console.log(...);` line. I have just copy-pasted this line from the exercise description, and there, the semicolon is missing. 

**Edit:** typos
