### ISSUE TITLE
learnyounode syntax error in learnyounode/node_modules/@hapi/joi/lib/index.js:36

### ISSUE THREAD

**Issue by chaikens** [nodeschool/discussions#2493]
#1728 # Error output
```
seth@turtle:~$ learnyounode
/usr/local/lib/node_modules/learnyounode/node_modules/@hapi/joi/lib/index.js:36
    return schema._init(...args);
                        ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/learnyounode/node_modules/explicit/lib/validate/index.js:3:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
seth@turtle:~$ node -v
v4.2.6
seth@turtle:~$ npm -v
3.5.2
seth@turtle:~$ 
```
l

**Comment by chaikens** [comment]
Fixed..I updated node to 12.16.2 and npm to 6.14.4
