### ISSUE TITLE
Cannot open the 2 - 8 and 11th exercise of "promise it wont hurt"

### ISSUE THREAD

**Issue by ghost** [nodeschool/discussions#2562]
* node version: v14.16.0
* npm version:  6.14.11
* os: windows 10 ltsb

### Error output
```
C:\Users\Adam\AppData\Roaming\npm\node_modules\promise-it-wont-hurt\node_modules\@timothygu\workshopper-wrappedexec\wrappedexec.js:16
  var dataPath = path.join(os.tmpDir(), '~workshopper.wraptmp.' + process.pid)
                              ^

TypeError: os.tmpDir is not a function
    at fix (C:\Users\Adam\AppData\Roaming\npm\node_modules\promise-it-wont-hurt\node_modules\@timothygu\workshopper-wrappedexec\wrappedexec.js:16:31)
    at wrappedexec (C:\Users\Adam\AppData\Roaming\npm\node_modules\promise-it-wont-hurt\node_modules\@timothygu\workshopper-wrappedexec\wrappedexec.js:93:5)
    at Object.<anonymous> (C:\Users\Adam\AppData\Roaming\npm\node_modules\promise-it-wont-hurt\exercises\fulfill_a_promise\exercise.js:27:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Workshopper.loadExercise (C:\Users\Adam\AppData\Roaming\npm\node_modules\promise-it-wont-hurt\node_modules\@timothygu\workshopper\workshopper.js:484:14)
```
The error output is the same troughout all the exercises that dont work

**Comment by ghost** [comment]
Fixed the issue by adding 'os.tmpDir = os.tmpdir;' on line 13 in the file wrappedexec.js at paht "AppData\Roaming\npm\node_modules\promise-it-wont-hurt\node_modules\@timothygu\workshopper-wrappedexec"

No idea why it works xd
