### ISSUE TITLE
Unexpected token error on instantiating  learnyounode 

### ISSUE THREAD

**Issue by pranaygoyal02** [nodeschool/discussions#2568]
### Unexpected token error on instantiating  learnyounode 
I did an installation of learnyounode with the command 
 ```  npm install - g learnyounode ```
* node version: v6.17.1
* npm version:  3.10.10
* os: Mac

### Error output
```
$ learnyounode
/Users/xxxl/.nvm/versions/node/v6.17.1/lib/node_modules/learnyounode/node_modules/@hapi/joi/lib/types/object/index.js:255
                        !pattern.schema._validate(key, state, { ...options, abortEarly:true }).errors) {
                                                                ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/xxx/.nvm/versions/node/v6.17.1/lib/node_modules/learnyounode/node_modules/@hapi/joi/lib/types/func/index.js:5:20)
```

**Comment by nabil-e** [comment]
hi,
try this: npm install -g learnyounode 
instead of this: npm install **- g** learnyounode
