### ISSUE TITLE
stream-adventure duplexer-redux error

### ISSUE THREAD

**Issue by univ1** [nodeschool/discussions#2574]
I frequently try to use stream-adventure verify <file-name> as a tool to check on progress. However, on this specific challenge,
no matter what my code looks like, I keep getting this error, which prevents me from logging stuff to the console, debugging, etc.

this.submissionChild.stdin = this.submissionChild
                                          
TypeError: Cannot set property 'stdin' of undefined
    at Exercise.<anonymous> (C:\Users\Absolute\AppData\Roaming\npm\node_modules\stream-adventure\lib\exportFnExercise.js:32:30)
    at next (C:\Users\Absolute\AppData\Roaming\npm\node_modules\stream-adventure\node_modules\workshopper-exercise\exercise.js:170:19)
    at Exercise.process (C:\Users\Absolute\AppData\Roaming\npm\node_modules\stream-adventure\node_modules\workshopper-exercise\exercise.js:177:5)
    at Exercise.<anonymous> (C:\Users\Absolute\AppData\Roaming\npm\node_modules\stream-adventure\node_modules\workshopper-exercise\exercise.js:147:10)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)

I'll get the error even if the file is empty. Does anyone have any idea why this is happening/how to fix it?

**Comment by univ1** [comment]
I got the error message to disappear and since have solved the challenge. This error message seems to pop up before a call to counter.setCounts(obj) is made.
