### ISSUE TITLE
Hi i'm totally new and I'm trying going through javascripting challenges, i'm stuck at lvl 15 "Objects"

### ISSUE THREAD

**Issue by GiuseppeHGpro** [nodeschool/discussions#2580]
I really don't know what is wrong

### Error output
```
 Error: Command failed: node "C:\Users\Peppe\Desktop\Prove\objects.js"
C:\Users\Peppe\Desktop\Prove\objects.js:3
  crust: 'deep dish',
  ^^^^^

SyntaxError: Unexpected identifier
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47

    at ChildProcess.exithandler (child_process.js:319:12)
    at ChildProcess.emit (events.js:375:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node "C:\\Users\\Peppe\\Desktop\\Prove\\objects.js"'
```

### My Code
```js
const pizza = {
  toppings: ['cheese', 'sauce', 'pepperoni']
  crust: 'deep dish',
  serves: 2
};
console.log(pizza);
```

**Comment by kishorsharma** [comment]
```js
const pizza = {
  toppings: ['cheese', 'sauce', 'pepperoni'], // <- missing comma
  crust: 'deep dish',
  serves: 2
};
console.log(pizza);
```
