### ISSUE TITLE
learn-sass not working - ENOENT Node-sass package

### ISSUE THREAD

**Issue by aymenBenadra** [nodeschool/discussions#2586]
### Issue description

I installed learn-sass with administrator privileges and without and installed node-sass with npm and yarn but it seems the ENOENT issue won't be going away. Can someone help?

### If you have a problem with an error message:

* node version: v14.16.0
* npm version:  6.14.11
* os: windows 10 21H1 

### Error output
```
C:\Users\Administrator\Desktop\learn-sass>learn-sass verify stylesheet.scss
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\Administrator\AppData\Roaming\npm\node_modules\learn-sass\node_modules\node-sass\bin\node-sass ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\learn-sass\\node_modules\\node-sass\\bin\\node-sass',
  path: 'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\learn-sass\\node_modules\\node-sass\\bin\\node-sass',
  spawnargs: [ 'stylesheet.scss' ]
}
```

### My Code
```scss
$color: #000;

body {
  color: $color;
}

```

**Comment by aymenBenadra** [comment]
Added useful information on the issue
