### ISSUE TITLE
SyntaxError: Invalid regular expression: missing /

### ISSUE THREAD

**Issue by sleepingcat4** [nodeschool/discussions#2605]
* node version: v14.18.0
* npm version:  8.4.1
* os: Windows 11

**### Error output**
```
app.use(express.static(path.join(__dirname*/public)));
                                           ^

SyntaxError: Invalid regular expression: missing /
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```
### My Code
**server.js**

```
const express = require("express");
const path = require("path");

const app = express();
const server = require("http").createServer(app);

const io = require("socket.io")(server);

app.use(express.static(path.join(__dirname+"/public")));

io.on("connection", function(socket){
	socket.on("newuser",function(username){
		socket.broadcast.emit("update", username + " joined the conversation");
	});
	socket.on("exituser",function(username){
		socket.broadcast.emit("update", username + " left the conversation");
	});
	socket.on("chat",function(message){
		socket.broadcast.emit("chat", message);
	});
});

server.listen(5000);

```
Despite I had updated and saved the code still it was showing the error. For some reason node was not picking up the new code update on terminal.

**Comment by rclements23** [comment]
no comments hmm same problem here

**Comment by sleepingcat4** [comment]
did you try downgrading the node version? btw what node version you're on? @rclements23
