### ISSUE TITLE
Additional on(error) for HTTP CLIENT official solution

### ISSUE THREAD

**Issue by dja014** [nodeschool/discussions#566]
First, let me say that I am lovin' your learnyounode tutorial.

However, in the 'HTTP CLIENT' step, you show the following as the official solution:

    var http = require('http')

    http.get(process.argv[2], function (response) {
      response.setEncoding('utf8')
      response.on('data', console.log)
      response.on('error', console.error)
    })

But when I tested it on an undefined URL string I got:

    events.js:72
            throw er; // Unhandled 'error' event
                  ^
    Error: connect ECONNREFUSED
        at errnoException (net.js:904:11)
        at Object.afterConnect [as oncomplete] (net.js:895:19)

I had to change it to the following to get it to work as expected in that case:

    var http = require('http')

    http.get(process.argv[2], function (response) {
      response.setEncoding('utf8')
      response.on('data', console.log)
      response.on('error', console.error)
    }).on('error', console.error)

I am still trying to figure out whether the second on(error) is redundant, or if you really need both (one for the synchronous get call, and the other for error events from the stream).

This is pretty nit-picky, sorry about that.
In any case, keep up the great work.

**Comment by dja014** [comment]
Hi-Based on the responses, it needed to be closed.I only intended to send a message to the tutorial authors that their recommended answer was wrong, but it was not interpreted that way.I do thank you for the clarification of the need to catch errors for both streams.However, as you guessed, that is what I figured all along.Later.Don
 


     On Tuesday, April 14, 2015 9:17 AM, Finn Pauls <notifications@github.com> wrote:
   

 Closed #566.—
