### ISSUE TITLE
HTTPclient exercise will not run

### ISSUE THREAD

**Issue by emlmarck** [nodeschool/discussions#769]
Hello I have been trying to run the HttpClient tutorial with the following code:
```javascript 
    //myHTTPclient.js
    var http = require('http');
    var URL = process.argv[2]
    http.get(URL, function(response) { 
    response.setEncoding('utf8');
    response.on('data', function(data){
	console.log('BODY: ' + data.toString());
    });
    response.on('error', console.error)
    }).on('error',console.error)
```
However, when I try to run
    
    learnyounode run myHTTPclient.js

I get this response from the terminal:

```
/usr/local/lib/node_modules/learnyounode/exercises/http_client/exercise.js:52
  this.server.close(callback)
              ^
TypeError: Cannot call method 'close' of undefined
    at Exercise.module.exports (/usr/local/lib/node_modules/learnyounode/exercises/http_client/exercise.js:52:15)
    at next (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:212:17)
    at Exercise.end (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:218:5)
    at Workshopper.end (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper/workshopper.js:163:12)
    at Workshopper.done (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper/workshopper.js:298:19)
    at Exercise.<anonymous> (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:123:14)
    at /usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:110:16
    at /usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/filecheck.js:9:14
    at Object.oncomplete (fs.js:107:15)
```

Is there something wrong with my setup? Is there something wrong with the files for this exercise?

I am running npm v 1.4.28 and learnyounode v 1.0.6

Thanks for your help

**Comment by a0viedo** [comment]
@zeroEvidence I'm in v0.10.35 using nvm and verifying your code. I couldn't reproduce your error. What are you running to verify your solution?

**Comment by martinheidegger** [comment]
@zeroEvidence Learnyounode received a major update, can you still reproduce that problem?

**Comment by xhocquet** [comment]
Just for anyone else running into this problem, a previous fellow and myself both figured out this error happens if you're just running the script from a wrong directory. Double check!
