### ISSUE TITLE
makemehapi : hellohapi. Somewhere a error ? 

### ISSUE THREAD

**Issue by roelof1967** [nodeschool/discussions#805]
Hello, 

I can do all the exercises but on this one I see a connecttion refused.
My code is : 

~~~

var Hapi = require('hapi'); 

var server = new Hapi.Server(); 

server.connection ( {
  host: 'http://intense-motor-47-180577.euw1-2.nitrousbox.com/', 
  port: Number(process.argv[2] || 3000)
}); 

server.route({
  path: '/', method:'GET',
  handler: console.log('Hello Hapi')
}); 

server.start(); 

~~~

I wonder if I made any error somewhere ? 

Roelof

**Comment by roelof1967** [comment]
Changed it locally to this : 

~~~

var Hapi = require('hapi'); 

var server = new Hapi.Server(); 

server.connection ( {
  host: 'localhost', 
  port: Number(process.argv[2] || 3000)
}); 

server.route({
  path: '/', method:'GET',
  handler: function handler(request, reply) {
    reply ('hello hapi'); 
  }
}); 

server.start(); 

~~~

but still this error : 

~~~

✗ Error connecting to http://localhost:11203: ECONNREFUSED                                                                                                                             
                                                                                                                                                                                       
Error: connect ECONNREFUSED                                                                                                                                                            
    at errnoException (net.js:904:11)                                                                                                                                                  
    at Object.afterConnect [as oncomplete] (net.js:895:19)  

~~~

Roelof

**Comment by martinheidegger** [comment]
Maybe too many servers running? Reboot?

**Comment by roelof1967** [comment]
Tried on both nitrious.io and locally on Fedora Linux and both gives after a reboot still the same error.

**Comment by roelof1967** [comment]
Another question  : What do I have to change to make use of get-port instead of a random port ?

**Comment by roelof1967** [comment]
Closed because of this bug : https://github.com/hapijs/makemehapi/issues/98
