### ISSUE TITLE
Error: write EPIPE running stream adventure transform 

### ISSUE THREAD

**Issue by vsellen** [nodeschool/discussions#812]
When I run the transform challenge solution I get the error below. I used the suggested solution to make sure it wasn't something in my code:

```javascript
var through = require('through');
process.stdin.pipe(through(function (buf) {
  this.queue(buf.toString().toUpperCase());
})).pipe(process.stdout);
```
 
OS windows 7 64 bit; node = v0.10.35; npm = 1.4.28 

c:\workspace_web\stream-adventure>stream-adventure verify transform.js
ACTUAL                             EXPECTED
------                             --------

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: write EPIPE
    at errnoException (net.js:905:11)
    at Socket._write (net.js:646:26)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at Socket.Writable.write (_stream_writable.js:183:11)
    at Socket.write (net.js:616:40)
    at Stream.ondata (stream.js:51:26)
    at Stream.emit (events.js:117:20)
    at drain (C:\Users\_____\AppData\Roaming\npm\node_modules\stream-adventure\
node_modules\through\index.js:36:16)
    at Stream.stream.queue.stream.push (C:\Users\_____\AppData\Roaming\npm\node
_modules\stream-adventure\node_modules\through\index.js:45:5)

**Comment by vsellen** [comment]
I re-installed transform and the solution worked. Thanks.
