### ISSUE TITLE
stream-adventure / transform   : Unhandled stream error in pipe. 

### ISSUE THREAD

**Issue by roelof1967** [nodeschool/discussions#816]
I have this solution : 

~ ~ ~ 

    var through = require('through');
    
    var tr = through(function write(data) {
            this.queue(data.toString().toUpperCase())
        },
        function end () {
            this.queue(null)
        })
    
    process.stdin.pipe(tr).pipe(process.stdout);

but as soon as I do stream-adventure verify transform.js I see this error :+1: 

    stream-adventure verify transform.js 
    ACTUAL                             EXPECTED
-    -----                             --------
    
    stream.js:94
          throw er; // Unhandled stream error in pipe.
               ^
    Error: read ECONNRESET
        at errnoException (net.js:904:11)
        at Pipe.onread (net.js:558:19)

**Comment by roelof1967** [comment]
Found it myself. Through was not installed properly
