### ISSUE TITLE
stream adventure websockets problem

### ISSUE THREAD

**Issue by cpmame** [nodeschool/discussions#885]
The solution does not work and I am not sure what went wrong. Please help...
```
// filename = 9.WebSockets.js
var ws = require('websocket-stream');
var stream = ws('ws://localhost:8000');
stream.end('hello\n');
```

When I run with "stream-adventure **verify** 9.WebSockets.js" here is what I got:
```
ACTUAL                             EXPECTED
------                             --------
""                             !== "ikeos."                      
null                           !== "uj"                          
null                           !== "ocndegcndw"                  
null                           !== "ocndegcndw"                  
null                           !== "xuy"                         
null                           !== "vcavzuwd"                    
null                           !== "gcand"                       
null                           !== "uj"                          
null                           !== "uj"                          
null                           !== ""                            
# FAIL

Your solution didn't match the expected output.
Try again, or run `stream-adventure run program.js` to see your solution's output.
```

When I run with "stream-adventure **run** 9.WebSockets.js" I got this:
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: socket hang up
    at createHangUpError (http.js:1476:15)
    at Socket.socketOnEnd (http.js:1572:23)
    at Socket.g (events.js:180:16)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
```

**Comment by cpmame** [comment]
Reinstalling the stream-adventure fixed the problem.
```
npm install -g stream-adventure
```
