### ISSUE TITLE
Error with juggling_asynch

### ISSUE THREAD

**Issue by pferguso6222** [nodeschool/discussions#934]
I think there is a problem with the tutorial.  I get the following output:

```
learnyounode verify jugglingAsynch.js
/usr/local/lib/node_modules/learnyounode/exercises/juggling_async/exercise.js:87
  this.servers.forEach(function (s) {
              ^
TypeError: Cannot read property 'forEach' of undefined
    at Exercise.<anonymous> (/usr/local/lib/node_modules/learnyounode/exercises/juggling_async/exercise.js:87:15)
    at next (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:260:17)
    at Exercise.end (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:266:5)
    at Workshopper.end (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper/workshopper.js:197:12)
    at Workshopper.done (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper/workshopper.js:329:19)
    at Exercise.<anonymous> (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:149:14)
    at /usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:136:16
    at Exercise.<anonymous> (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/filecheck.js:10:14)
    at FSReqWrap.oncomplete (fs.js:99:15)
```

**Comment by notmatt** [comment]
@pferguso6222 I wasn't able to reproduce this except by attempting to verify a non-existent file, so the first thing to check is if you're in the right directory, don't have a typo in the file name and so on. 

Assuming it's not that, could you post your solution? It may let me (or someone else) give better advice, or narrow down the problem.

Also, are you able to verify the included solution, like so:
```
learnyounode verify /usr/local/lib/node_modules/learnyounode/exercises/juggling_async/solution/solution.js
```
That assumes you're on a unix-y system (OSX, BSD, Linux, etc), and installed the workshop in the recommended way (`npm install learnyouanode -g`); sorry I don't know where the solution gets installed by default in Windows, but you can manually download it [from here](https://raw.githubusercontent.com/rvagg/learnyounode/master/exercises/juggling_async/solution/solution.js).

**Comment by martinheidegger** [comment]
@pferguso6222 Did that help you?
