### ISSUE TITLE
trouble starting javascripting/learnyounode workshops

### ISSUE THREAD

**Issue by zhark90** [nodeschool/discussions#993]
Hey there!
I'm new to JavaScript and Node and having trouble with starting Javascripting/Learnyounode Workshops

Here are the errors:
```
$ learnyounode
C:\Users\Paul\AppData\Roaming\npm\node_modules\learnyounode\node_modules\workshopper\node_modules\terminal-menu\index.js:61
    process.stdin.setRawMode(true);
                  ^
TypeError: undefined is not a function
    at new Menu (C:\Users\Paul\AppData\Roaming\npm\node_modules\learnyounode\node_modules\workshopper\node_modules\terminal-menu\index.js:61:19)
    at module.exports (C:\Users\Paul\AppData\Roaming\npm\node_modules\learnyounode\node_modules\workshopper\node_modules\terminal-menu\index.js:8:12)
    at showMenu (C:\Users\Paul\AppData\Roaming\npm\node_modules\learnyounode\node_modules\workshopper\menu.js:16:25)
    at showMenu (C:\Users\Paul\AppData\Roaming\npm\node_modules\learnyounode\node_modules\workshopper\exerciseMenu.js:29:10)
    at Workshopper.printMenu (C:\Users\Paul\AppData\Roaming\npm\node_modules\learnyounode\node_modules\workshopper\workshopper.js:365:14)
    at new Workshopper (C:\Users\Paul\AppData\Roaming\npm\node_modules\learnyounode\node_modules\workshopper\workshopper.js:190:8)
    at Workshopper (C:\Users\Paul\AppData\Roaming\npm\node_modules\learnyounode\node_modules\workshopper\workshopper.js:20:12)
    at Object.<anonymous> (C:\Users\Paul\AppData\Roaming\npm\node_modules\learnyounode\learnyounode.js:11:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```
```
$ javascripting
C:\Users\Paul\AppData\Roaming\npm\node_modules\javascripting\node_modules\adventure\lib\menu.js:51
    process.stdin.setRawMode(true);
                  ^
TypeError: undefined is not a function
    at module.exports (C:\Users\Paul\AppData\Roaming\npm\node_modules\javascripting\node_modules\adventure\lib\menu.js:51:19)
    at Shop.showMenu (C:\Users\Paul\AppData\Roaming\npm\node_modules\javascripting\node_modules\adventure\index.js:258:16)
    at Shop.execute (C:\Users\Paul\AppData\Roaming\npm\node_modules\javascripting\node_modules\adventure\index.js:122:14)
    at Object.<anonymous> (C:\Users\Paul\AppData\Roaming\npm\node_modules\javascripting\index.js:15:7)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
```
````
$ node -v
v0.12.0
$ npm -v
2.5.1
$ learnyounode -v
learnyounode@2.5.0

````
Thanks in advance! :)

**Comment by finnp** [comment]
It's probably because of cygwin: https://github.com/nodeschool/discussions/issues/12

**Comment by finnp** [comment]
Here's the link to the git installer: http://git-scm.com/download/win

**Comment by nsp** [comment]
This happens when the terminal does not support raw mode (Cygwin for #12, emacs for me). Can you catch this and include a more helpful error message? Save n00bs a Google?

Something along the lines of: 

    It appears that your terminal does not support "raw" input. Terminals that are known to work include:
    * Node.js Command Prompt (Windows)
    * Terminator (Linux)
    * Whatever else

Thanks!
