### ISSUE TITLE
cannot install levelmeup on windows 7

### ISSUE THREAD

**Issue by PetraBaum** [nodeschool/discussions#997]
Hello.
I am having trouble installing levelmeup. I was able to install javascripting and learnyounode earlier. After installing what node-gyp requires, i am also able to install levelup and node-gyp. Still, levelmeup fails to build.
I am running windows 7 64 bit.
the errors:
```
C:\Windows\system32>npm install -g levelmeup
npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys
-


> leveldown@0.10.4 install C:\Users\Constantin\AppData\Roaming\npm\node_modules\levelmeup\node_modules\level\node_modules\leveldown
> node-gyp rebuild


C:\Users\Constantin\AppData\Roaming\npm\node_modules\levelmeup\node_modules\level\node_modules\leveldown>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please
install Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...". [C:\Users\Constantin\AppData
\Roaming\npm\node_modules\levelmeup\node_modules\level\node_modules\leveldown\deps\leveldb\leveldb.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please
install Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...". [C:\Users\Constantin\AppData
\Roaming\npm\node_modules\levelmeup\node_modules\level\node_modules\leveldown\deps\snappy\snappy.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Constantin\AppData\Roaming\npm\node_modules\levelmeup\node_modules\level\node_modules\leveldown
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
npm ERR! leveldown@0.10.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldown@0.10.4 install script.
npm ERR! This is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "levelmeup"
npm ERR! cwd C:\Windows\system32
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by martinheidegger** [comment]
What is the output of `node-gyp rebuild`?

**Comment by PetraBaum** [comment]
where to execute that?
```
C:\Windows\system32>node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.3
gyp info using node@0.10.32 | win32 | x64
gyp info spawn C:\Program Files (x86)\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\Constantin\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Windows\\system32\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Constantin\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Constantin\\.node-gyp\\0.10.32\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Constantin\\.node-gyp\\0.10.32',
gyp info spawn args   '-Dmodule_root_dir=C:\\Windows\\system32',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Windows\\system32\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: C:\Windows\system32) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Constantin\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Users\\Constantin\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Windows\system32
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.3
```

**Comment by SomeoneWeird** [comment]
Please follow the [Windows Installation Instructions](https://github.com/TooTallNate/node-gyp#installation) for the dependencies you need, if you haven't already.

**Comment by PetraBaum** [comment]
I have allready. somehow. I reinstalled the tools and after fixing an missing ammintrin.h error it now gives a different error.
```
D:\test\school and stuff\node_modules\node-leveldown>node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.3
gyp info using node@0.10.32 | win32 | x64
gyp info spawn C:\Program Files (x86)\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\Constantin\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gy
p_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\test\\school and stuff\\node_modules\\node-leveldown\\build\\config.gypi'
,
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Constantin\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.g
ypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Constantin\\.node-gyp\\0.10.32\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Constantin\\.node-gyp\\0.10.32',
gyp info spawn args   '-Dmodule_root_dir=D:\\test\\school and stuff\\node_modules\\node-leveldown',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\test\\school and stuff\\node_modules\\node-leveldown\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu er
möglichen, müssen Sie den Schalter "/m" hinzufügen.
LIB : fatal error C1900: Il mismatch between 'P1' version '20100826' and 'P2' version '20081201' [D
:\test\school and stuff\node_modules\node-leveldown\deps\leveldb\leveldb.vcxproj]
LINK : fatal error LNK1257: code generation failed [D:\test\school and stuff\node_modules\node-leve
ldown\deps\leveldb\leveldb.vcxproj]
LIB : fatal error C1900: Il mismatch between 'P1' version '20100826' and 'P2' version '20081201' [D
:\test\school and stuff\node_modules\node-leveldown\deps\snappy\snappy.vcxproj]
LINK : fatal error LNK1257: code generation failed [D:\test\school and stuff\node_modules\node-leve
ldown\deps\snappy\snappy.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1

gyp ERR! stack     at ChildProcess.onExit (C:\Users\Constantin\AppData\Roaming\npm\node_modules\node
-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Users\\Constantin\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\
node-gyp.js" "rebuild"
gyp ERR! cwd D:\test\school and stuff\node_modules\node-leveldown
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok


```

**Comment by martinheidegger** [comment]
It seems like you have built some libraries with different versions of the Microsoft compiler and the compiler is complaining about it. Maybe if you were to delete all files in `npm root -g` and install again it could work.
